### PR TITLE
All tab

### LINKED ISSUE #102: [Audio] Create "all" view in UI
We need to update the search routes for audio support:

- [x] Add an "all" tab in the UI, instead of `/search` and `/search/image` sharing the "Image" tab
- [x] Make `/search` a copy of `/search/image' for now

### PR DESCRIPTION
**Pull request by obulat**
Fixes #102 

To prepare for Audio addition, this PR adds the default search tab 'All' to the current 'Image', 'Audio' and 'Video'.  Currently, the content of the 'All' tab is the same as the content of 'Image' tab:

Screen Shot 2021-08-02 at 3 04 41 PM

### CODE REVIEW

**Comment by dhruvkb** [comment]
I think you should change the target branch to `audio` (#101).

**Comment by zackkrida** [comment]
@obulat Looks like a git issue where all of the Tailwind work was captured in this PR too

**Comment by dhruvkb** [comment]
@zackkrida it seems that Olga did branch out from `main` but after the Tailwind commits were merged into it. The target branch `audio` does not have those Tailwind commits so they're showing up here.

**Comment by zackkrida** [comment]
Very weird. The audio branch was rebased to include the tailwind work, but it still showed those commits here. I un-set and re-set the base branch on this PR and now it appears correctly.

**Review by zackkrida — APPROVED** [review]

**Review by dhruvkb — APPROVED** [review]
Looks good 👍!

**Review by krysal — APPROVED** [review]

**Pull request merged**
