### PR TITLE
Try publishing Storybook/Tailwind config previews per PR

### LINKED ISSUE #1326: Deploy storybook for PRs
## Problem

To checkout the storybook for a branch you currently have to check out the branch and build storybook locally. This is a hindrance for non-devs to contribute to things like design iteration.

Also, if you're reviewing a PR that adds or modifies a story and also makes changes to the Nuxt app, that means you have to checkout the branch and run both `pnpm storybook` and `pnpm dev` to fully review the PR. If we can cut out one of those steps to make it easier for reviewers that would be great, in my opinion.

## Description

Deploying storybook for each PR feels like less of a hurdle than deploying the whole application for each PR (which would be nice, but I think that's something far down the road for the project at the moment).

I _think_ we could do it something like this in a new PR workflow:

1. Build storybook and tailwind config the way we do in the main GitHub pages action
2. Save the output as an artifact
3. Checkout the gh-pages branch and create a sub-folder using the PR number and unzip the saved artifact into that folder

The outstanding question for me is how we prevent the existing GH pages workflow from trampling those subfolders. Currently the entire contents of the `gh-pages` branch is replaced with the output of building storybook and the tailwind config viewer.

Should we also sub-folder the main branch in this way, so that the main storybook would be at https://wordpress.github.io/openverse-frontend/main? We could create an `index.html` page that redirects to that automatically using JavaScript or, if gh pages supports it, actual redirect headers.

The branch workflow should also post the link to the storybook as a comment and (preferably) update the comment accordingly when a new revision is pushed to the PR to indicate whether the storybook is in the process of being updated or if it's already been updated for the latest commit in the PR. Likewise, we should have a supplemental workflow to delete the storybook for branches after they're merged.

The comment left on the PR should indicate that the link is only valid as long as the PR stays open.

## Alternatives

Use something like Vercel or Netlify to automatically do all of this for us including PR preview deploys without having to juggle the `gh-pages` branch all over the place and manage the clean up.

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

### PR DESCRIPTION
**Pull request by sarayourfriend**
## Fixes

Fixes #1326 by @sarayourfriend 

## Description

Deploys Storybook and Tailwind previews to GitHub pages for each PR in a subdirectory on GitHub pages.

## Testing Instructions

Not sure really how to test it, but you can see it worked on this PR :slightly_smiling_face: 

We will need to verify that the clean up step actually works after this is merged. The goal there is to prevent our `gh-pages` branch from becoming stuffed with tons of old no-longer-relevant JavaScript.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [x] My pull request targets the *default* branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [N/A] I added or updated tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [N/A] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by sarayourfriend** [comment]
Note that if other PRs get merged before this one, then the preview links in the comment probably won't work because the current action to publish the `main` GH pages replaces all files in the `gh-pages` branch and therefore tramples over this one. This PR updates it so that doesn't happen.

**Review by obulat — APPROVED** [review]
This is really nice!
It will also help us not to neglect storybook :)

**Comment by sarayourfriend** [comment]
@WordPress/openverse-developers This PR just modifies/adds GitHub actions so could be reviewed by anyone on the team, no frontend knowledge needed for this one but it would be a great devex boost for the frontend repository.

**Review by AetherUnbound — APPROVED** [review]
This is so incredibly cool! 🚀

**Pull request merged**
