### PR TITLE
Add description to the home page

### LINKED ISSUE #1756: Update the homepage description
## Description

The description below the Openverse logo on the homepage needs to be updated.

The new text is "Discover more than 600 million media to use", and the styles are as follows:
All fonts are Inter, style Regular.
### Desktop
**Subtitle**
Font size: 46px
Line height: 60px
Line height: 130%
Margin-bottom: 16px

**Description**
Font size: 27px
Line height: 35px
Line height: 130%
Margin-bottom: 24px

### Mobile
**Subtitle**
Font size: 19px
Line height: 25px
Line height: 130%
Margin-bottom: 24px

**Description**
Font size: 14px
Line height: 22px
Line height: 160%
Margin-bottom: 32px

## Screenshots
 
Screen Shot 2022-09-06 at 7 26 01 PM

## Mockups
* Figma: [Copy improvements in the search flow](https://www.figma.com/file/ClEKESZzZxudMoHbHq3A66/Copy-improvements-in-the-search-flow?node-id=0%3A1)
* Presentation: [Slides](https://www.figma.com/proto/ClEKESZzZxudMoHbHq3A66/Copy-improvements-in-the-search-flow?page-id=26%3A13657&node-id=427%3A9251&viewport=461%2C537%2C0.3&scaling=min-zoom&starting-point-node-id=427%3A9251)

### PR DESCRIPTION
**Pull request by obulat**
## Fixes

Fixes #1756 by @panchovm

## Description

This PR adds the text changes from the linked issue to the homepage.
@panchovm, I've noticed that the font sizes are not multiples of 16 here, as they normally are. 
I've also changed the font sizes on the `md` breakpoint, not on the `lg` breakpoint as it was previously. Is that correct, or should I change it back to `lg`?

## Checklist

- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [ ] My pull request targets the *default* branch of the repository (`main`) or a parent feature branch.
- [ ] My commit messages follow [best practices][best_practices].
- [ ] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by zackkrida — CHANGES_REQUESTED** [review]
Looks fantastic, @obulat. One change in the new design that is missing is that the logo size is reduced, and it is left-aligned with the text, rather than the logomark 'floating' to the left of the texts.

**Review by zackkrida — APPROVED** [review]
Looks great! I'll leave any major design suggestions to @panchovm. 
One thing that I'm noticing that pre-exists this PR, so can be handled in a separate issue, is that the logo alignment on the homepage doesn't match the header in the rest of the site.

**Review by panchovm — CHANGES_REQUESTED** [review]
Please address the margin-left comment mentioned before.

**Comment by zackkrida** [comment]
I updated the width and this is ready for review again, @panchovm. Here is a gif:

CleanShot 2022-09-07 at 15 12 50

**Review by panchovm — APPROVED** [review]
It looks great. Thank you all for the work made ✨

**Pull request merged**
