### PR TITLE
TSify dialog composables

### PR DESCRIPTION
**Pull request by sarayourfriend**
## Fixes

Fixes #[issue number] by @[issue author]

## Checklist

- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [ ] My pull request targets the *default* branch of the repository (`main`) or a parent feature branch.
- [ ] My commit messages follow [best practices][best_practices].
- [ ] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by sarayourfriend** [comment]
I'm going to put this PR on hold until I've merged https://github.com/WordPress/openverse-frontend/pull/1275 as 1275 updates and fixes some of the initial focus handling to be more robust than it is now and this PR currently has issues with the focus management having changed for some reason.

I can't figure out why it changed as there aren't any runtime changes that would suggest it, so the only thing I can think is that the ariakit utilities copied into this PR are slightly different than the version being pulled from NPM in our pnpm-lock, I just haven't taken the time to manually diff them yet.

**Comment by AetherUnbound** [comment]
@sarayourfriend is the work on this unblocked? It looks like there are a few conflicts, should this draft remain open?

**Comment by sarayourfriend** [comment]
I think this can be rebased and undrafted. The issue that was blocking it was actually one already present in main and Olga found another fix for it.

**Comment by sarayourfriend** [comment]
Sorry, I misremembered what was blocking this. It's still blocked and cannot be undrafted yet.

**Comment by AetherUnbound** [comment]
Dang! What's the current blocker?

**Comment by sarayourfriend** [comment]
Still the same focus management issue. I have no idea how to solve it.

**Comment by sarayourfriend** [comment]
I'm not sure if it's worth focusing on this, or focusing on #1372 :shrug: I think the Ariakit PR has more value long term, but I also don't have the time currently to spend on it that it would need for it to even cover the dialog in a reasonable amount of time.

TSifying these files isn't critical though. There are other workarounds we can use to be able to TSify related files.

Gonna close this PR. Someone else can try this in a different PR or help out with the Ariakit one.

**Pull request closed without merging**
