### PR TITLE
Audio filters

### LINKED ISSUE #105: [Audio] Sidebar filters
Conditionally show relevant audio filters in the sidebar when switching to the `/search/audio` view.
We need to determine the full list of filters here:

- Use
- Licenses
- Category (music / sound effect / podcast)
- Source
- Genre (maybe?, via text input or something? too many to list in the sidebar)

We may want to choose a subset to display in our initial release, rather than all of our ideal items

### PR DESCRIPTION
**Pull request by obulat**
## Fixes

Fixes #105 by @zackkrida

## Description

This PR further refactors and simplifies handling of Filters, adds Audio to the side filters, and makes it easier to add other media type filters in the future.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [ ] My pull request targets the *default* branch of the repository (`main` or `master`).
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added or updated tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by zackkrida — CHANGES_REQUESTED** [review]
This looks really good so far—I rebased and force pushed your branch to clean up the commits. 

I also made a PR against your PR to add the right filters for video and fix some bugs. Please consider that PR as _review suggestions_ and merge it into yours if you approve, instead of following the usual PR merge process.

https://github.com/WordPress/openverse-frontend/pull/120

Once my changes are merged in and/or discussed I will approve this; thank you!

**Comment by obulat** [comment]
> This looks really good so far—I rebased and force pushed your branch to clean up the commits.
> 
> I also made a PR against your PR to add the right filters for video and fix some bugs. Please consider that PR as _review suggestions_ and merge it into yours if you approve, instead of following the usual PR merge process.
> 
> #120
> 
> Once my changes are merged in and/or discussed I will approve this; thank you!

Thank you for the review and bug fixing :)

I have merged your PR, and am going to remove the video-specific filters because without the actual functionality (searching by license type) they would just confuse the users.

I would prefer to rename the image-specific filters, such as `categories` and `extensions` to `imageCategories` and `imageExtensions` to make the naming consistent. I did not change it to avoid possible breakages and debugging. Is it a good idea to rename them in a future PR?

**Comment by zackkrida** [comment]
> Is it a good idea to rename them in a future PR?
Yes, I think it is a good idea!

As for those video filters, I used those because those are the filters that actually work with meta search (only the "use" ones)! I can see that it might be confusing to have so few visible though.

**Review by zackkrida — APPROVED** [review]

**Review by krysal — APPROVED** [review]
Awesome work! ✨

**Review by dhruvkb — APPROVED** [review]

**Pull request merged**
