### PR TITLE
Use popover for pages menu on screens betweween md and lg

### LINKED ISSUE #2013: Update header internal to use a popover between `sm` and `md`
Copied from #2009 

### Breakpoint change
To show all pages correctly in every breakpoint, the design proposes using the burger version in both `sm` and `md` breakpoints. However, the full-screen menu is shown differently in `md` to tap into the viewport's available space.

The menu popover has Popover item components to be consistent with the Design Library’s elements available. At the same time, the label of each item is based on the “Link” component mentioned above to keep consistency.

#### `sm`, `md` breakpoints
imagen

### PR DESCRIPTION
**Pull request by obulat**
## Fixes

Fixes #2013 by @obulat

## Description

This PR adds a popover for pages navigation in the `VHeaderInternal` for screens between `md` and `lg`.
I am drafting it because the styling of the pages popover will need to be tweaked to match the mockups.
It is based on #2050, and needs to be reviewed after it.

## Testing Instructions

Go to localhost:8443/preferences and check the New header checkmark. Try changing the screen widths and opening the pages modal/popup. If the screen width is below 768px, you should see a modal as on main currently. If the screen is above that, but below the `lg` breakpoint, you should see a popover.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like
      `Update index.md`).
- [x] My pull request targets the _default_ branch of the repository (`main`) or
      a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible
      errors.

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by panchovm** [comment]
It looks excellent. Just a few comments:
1. Popover menu should include `sm` breakpoint. Otherwise, it takes too much of the screen.
2. In `md`, right side of header should have a padding of `12px`. Spacings are slightly different between content and internal headers.
3. Bold style should be `600` instead of `700`
4. `external-link` icon should have its native `24px` size.
5. Since homepage redesign has `Black` as background color for the full-size menu, it would be great to update this version to match both designs.

I noticed there are top and bottom margins in `li` element defined in `.py-3` class. I wonder if we need that instead of flex with a `24px` row-gap.

CleanShot 2022-12-16 at 15 43 32@2x

I also wonder if we are approaching the i18n requirements correctly in cases where label lengths reach two lines and icon needs to be centrally aligned. In Figma, it looks like this.

CleanShot 2022-12-16 at 15 51 35@2x

## Nonblocker comments

On the other hand, the Openverse logo is now a [Figma component](https://www.figma.com/file/GIIQ4sDbaToCfFQyKMvzr8/Openverse-Design-Library?node-id=3835%3A11055&t=btcOlP5QElS5G299-4) with new padding values for the focus ring and slightly bigger. I will request adding the component in a new ticket

Openverse logo as Figma component

When scrolling down, I noticed the header does not have a border bottom. It'd be good to add a 1px of `dark-charcoal-20` like the content version.

CleanShot 2022-12-16 at 16 19 32@2x

**Review by panchovm — CHANGES_REQUESTED** [review]
Sorry for not replying from a requesting-changes comment 😅 , but acknowledging my points shared above.

**Review by panchovm — CHANGES_REQUESTED** [review]
It looks great ✨ Just one comment
* Bold style should be `600`. I am still seeing a font-weight of `700`.

Feel free to avoid it if we have plans for the upcoming text style consistency work.

**Comment by obulat** [comment]
> Bold style should be `600`. I am still seeing a font-weight of `700`.

Sorry, I couldn't find where the font weight was 700 previously :) Found and fixed!

**Review by panchovm — APPROVED** [review]
Great work ✨

**Review by dhruvkb — APPROVED** [review]

**Pull request merged**
