### PR TITLE
Heading order & formating fixed

### LINKED ISSUE #1617: Correct heading order for the Sources page
## Problem

The heading order on the Sources page (https://search.openverse.engineering/sources) is currently incorrect. `<h2>` is skipped.

## Description

The heading order should be logical (h1-h6), but the visual styles should still match the designs.

### PR DESCRIPTION
**Pull request by ramadanomar**
## Fixes
Fixes #1617 & #1618 by @obulat
See pr #1638 for more details.
## Description

Fixed heading order while maintaing css style according to figma document

## Testing Instructions

go to /sources and /extension pages
ExtensionWebsite-Site
ExtensionsDesktop
Screenshot-subtitle-extension
TypesExtensions

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [x] My pull request targets the *default* branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added or updated tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by zackkrida** [comment]
While I do ultimately want to remove this page, for the reasons described in #1648, it would be nice to merge this first in case we ever restore the page in the future 👍

**Review by obulat — APPROVED** [review]
This PR is great, @ramadanomar, thank you for your contribution 🎉

As @zackkrida mentioned, we are going to remove one of the pages touched in this PR. After the Openverse extension itself is updated, we'll add back the page for it :)

**Review by zackkrida — APPROVED** [review]
LGTM!

**Comment by dhruvkb** [comment]
It seems that this PR has broken our Playwright tests. Maybe it was not updated after @obulat's corrected the Playwright workflow (issue #1637, PR #1640).

**Pull request merged**
