### PR TITLE
Update README.md to remove broken link

### LINKED ISSUE #494: Remove broken link from README
The text in the readme "You can learn more about the migration to Nuxt.js here." links to a broken page. We should remove that line.

### PR DESCRIPTION
**Pull request by amm98d**
## Fixes

Fixes #494 by @zackkrida 

## Description

The text in the readme "You can learn more about the migration to Nuxt.js here." links to a broken page. That has been removed.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [x] My pull request targets the *default* branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [ ] My code follows the established code style of the repository.
- [x] I added or updated tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by amm98d** [comment]
How do I add the PR labels, the ones whose checks are failing...

**Review by zackkrida — APPROVED** [review]
Thank you!

**Comment by zackkrida** [comment]
@amm98d Nice first contribution 😄 I've added the labels for you, you can do that in the sidebar of GitHub in the future:

CleanShot 2021-12-07 at 07 44 35@2x

**Comment by amm98d** [comment]
> @amm98d Nice first contribution 😄 I've added the labels for you, you can do that in the sidebar of GitHub in the future:

@zackkrida thanks! 
That's exactly where I was looking, for some reason, I am not getting that wheel icon in the sidebar 🤷‍♂️

**Comment by zackkrida** [comment]
@amm98d So you don't need to click the wheel—it's a bit unintuitive but you have to click the word 'Labels' which then shows you a dropdown of labels 😅

**Comment by amm98d** [comment]
> @amm98d So you don't need to click the wheel—it's a bit unintuitive but you have to click the word 'Labels' which then shows you a dropdown of labels 😅
> 
> But also, I think only members of the repository with the role `contributor` are allowed to label PRs in GitHub!

Right, makes sense. Well, thanks though!

**Review by dhruvkb — APPROVED** [review]

**Pull request merged**
