### PR TITLE
Use singular `category` API param

### LINKED ISSUE #1169: Audio category filter not working correctly
## Reproduction

1. Make an audio search, e.g.: https://wordpress.org/openverse/search/audio?q=coffee&categories=music
2. Observe there is a mix of audio categories in the results, in the case of the previous links: Music and Sound effects
3. Select a category, e.g.: **Music** and observe the empty results page appears
4. Deselect Music and try the **Sound effects** category, observe that results are still mixed with **Music** tracks.

## Expectation

Filters should reduce the number of results to the ones falling under the selected category.

## Environment

This happens in both, the production and the staging environment.

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

### PR DESCRIPTION
**Pull request by obulat**
## Fixes

Fixes #1169 by @krysal

## Description

This PR replaces plural API parameter `categories` with singular `category`, and updates some documentation.

This probably shouldn't be merged until the API fix is deployed because it will break the image category filtering.

## Testing Instructions

If you run this as is, filtering by category will return un-filtered result because the production API discards filters that don't exist. If you run it with API from https://github.com/WordPress/openverse-api/pull/583 running locally, you should get filtered results for audio and images.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [x] My pull request targets the *default* branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by obulat** [comment]
Noting here that I've marked this PR as low priority because without the deployment of API with the category fix, this would not fix anything, as the singular `category` parameter would be discarded by the API. And with the API fix deployed, current approach (with `categories` plural) will still work, and this PR aims for the future version of  the API where `categories` is deprecated.

**Comment by sarayourfriend** [comment]
Should we mark it back to low?

**Comment by krysal** [comment]
Honestly, I marked it as critical to highlight the dependency on the API and push the fix there 😆 Wouldn't it be better to use the singular version that we know is not deprecated? or is the intention to keep this open until we deprecated the plural field? 🤔

**Comment by obulat** [comment]
Great, I understand that it's actually a close to critical issue across the stack. The way the currently deployed API works, using singular `category` will cause an error, so it's not a good idea to merge this before API is deployed.

After the category fix in the API is deployed (I've merged it just now), both singular and plural versions will work, so then this fix can be applied and deployed.

When we finally change the version from `v1`, we can finally deprecate the plural `categories` parameter in the API.

**Comment by krysal** [comment]
That makes sense. BTW, everything looks good here, I reviewed using the local API with the fix but was almost impossible to find a term with mixed categories results so that could make time to try updating the API sample data too.

**Comment by zackkrida** [comment]
@obulat is this blocked until the API is deployed?

**Review by sarayourfriend — APPROVED** [review]
LGTM!

**Pull request merged**
