### PR TITLE
Create a page for the web extension

### LINKED ISSUE #87: Move the browser extension page from a standalone site to this project
The current browser extension page is at [opensource.creativecommons.org/ccsearch-browser-extension][cc-extension].
We want to move it to [wordpress.org/openverse][wp-ov] so a page for it should be created here.

[cc-extension]: https://opensource.creativecommons.org/ccsearch-browser-extension/
[wp-ov]: https://wordpress.org/openverse/

### PR DESCRIPTION
**Pull request by dhruvkb**
Fixes #87.

This PR creates the extension page inside the Openverse frontend.

### CODE REVIEW

**Comment by dhruvkb** [comment]
The PR currently uses placeholder boxes in place of the actual images.

**Comment by dhruvkb** [comment]
Looking pretty good with actual media.

image

**Review by zackkrida — DISMISSED** [review]
This looks great to me. Here's a test URL: https://openverse.zack.cat (CC @panchovm) 

Some small details:

- In the mockup the video is wider than the content above it, which looks really nice. I think even with the slightly blurry video, it looks good to give the video a max-width of 1200px, but I also see the argument to keep it the way it is. 
- [ ] The section with the image + content blocks needs more vertical padding (around 120px)
- [ ] "Have your favorite content" also needs additional whitespace at the bottom

**Review by krysal — DISMISSED** [review]
Looks great! @panchovm could give more detailed feedback here also.

**Comment by panchovm** [comment]
It looks excellent. Just a few comments:
1. I like @zackkrida's idea of keeping a max-width of 1200px.
2. Main title has H2 style, but heading styles changed and we should follow what we discussed in #90 
3. [Top padding](https://d.pr/i/ApjlLH) and bottom padding of where sections are should be `120px` (8 x 15).
4. The same applies between sections. Space must be `120px`.
5. All small images must have an inside border of 1px, `rgba(30, 30, 30, 0.2)`.
6. Descriptions below section titles should be `16px font-size` and `190% line-height`. Otherwise, font sizes will look too much different.

Thanks for the improvement.

**Review by zackkrida — APPROVED** [review]
L
G
T
M

**Review by krysal — APPROVED** [review]

**Pull request merged**
