### PR TITLE
Fixed Typo in README.md

### LINKED ISSUE #1533: Fix typo in Storybook references in README.md
## Description

https://github.com/WordPress/openverse-frontend/blob/main/README.md

> Typo: The sentence 'You can also view the production Storybook' is missing a period. Also, 'the production storybook' feels like an odd phrase, it might be better to explain what it is 'You can view a gallery of our frontend components on our Storybook', something like that.

Reported by @zackkrida 

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

### PR DESCRIPTION
**Pull request by PrajwalBorkar**
## Fixes

Fixes #1533 

## Checklist

- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [ ] My pull request targets the *default* branch of the repository (`main`) or a parent feature branch.
- [ ] My commit messages follow [best practices][best_practices].
- [ ] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by sarayourfriend** [comment]
@PrajwalBorkar thanks so much for the contribution and welcome to Openverse :slightly_smiling_face: Could you also update the text referring to the "production Storybook" based on the suggested changes in the issue? Thanks!

**Comment by PrajwalBorkar** [comment]
> @PrajwalBorkar thanks so much for the contribution and welcome to Openverse 🙂 Could you also update the text referring to the "production Storybook" based on the suggested changes in the issue? Thanks!

Review if any changes required.

**Review by sarayourfriend — APPROVED** [review]
Looks great, thanks again!

**Comment by sarayourfriend** [comment]
Once this gets another approval from one of the requested reviewers we'll get it merged quickly for you.

**Review by dhruvkb — APPROVED** [review]
Nicely done. I like the clearer description of what the Storybook is.

**Pull request merged**
