### PR TITLE
Tighten the condition for audio playback to continue across pages

### LINKED ISSUE #2118: Audio keeps playing on a single image result
## Description

On desktop, audio keeps playing when the image result is clicked after playing an audio from the results page.

## Reproduction

1. Search for something on desktop in the All content view.
2. Play a longer audio.
3. Click on an image result.
4. Hear error: the audio keeps playing, and there is no UI control for the user to stop it.

## Additional context
First reported by @dhruvkb.

### PR DESCRIPTION
**Pull request by dhruvkb**
## Fixes

Fixes #2118 by @obulat

## Description

This PR tightens the condition that allows playback to continue by using the router matching composable. This fixes the condition where audio playback would continue on any page.

## Testing Instructions

0. Check out the PR and run the dev server.
1. Search for a term.
2. Play an audio track.
3. Click on any other result (be it image or audio) to open the single result page. Audio playback should be stopped. (Technically you could navigate to any other page, even the home or content pages and the playback should stop).
4. Go back and resume the audio track again.
6. Click on the same result to open the single result page. Audio playback should continue from the same spot.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like
      `Update index.md`).
- [x] My pull request targets the _default_ branch of the repository (`main`) or
      a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible
      errors.

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by obulat — COMMENTED** [review]
Wouldn't we need to add the same handling to the `VGlobalAudioTrack`?

**Comment by dhruvkb** [comment]
This fix is not needed for the global audio player for these reasons:

The user cannot play a track from the mixed media results on mobile. The boxed audio player does not show that control.



If the user does open a track single result page and play an audio, going back stops the playback and hides global the audio player. Not a problem.

If you narrow down to just audio results, playing a track from the results is now possible.



In this case, if you play a track, the global audio player is shown and remains visible if you navigate to any other page. So it's okay to continue the playback as it can be paused by the user.

<sub>PS: There is an edge case issue that the global audio player remains visible across the site if you play a track and jump to the homepage using the logo but bringing that into the scope of this issue will prevent us from fixing the more likely issue. Also there has to be a way to handle all these audio shenanigans using a cleaner solution so I want to keep this fix simple.</sub>

**Review by obulat — APPROVED** [review]
The audio stops immediately 👍

**Review by zackkrida — APPROVED** [review]
LGTM. Appreciate the deliberate blocking of scope creep.

**Pull request merged**
