### PR TITLE
Redirect external sources

### LINKED ISSUE #1990: Set up redirect from `/external-sources` to `/about` page
## Problem

We are moving the text from the External sources page to the About page.

## Description

To make sure that we do not break any links, we need to setup the redirect from `/external-sources` page to the `/about` page for when the `new_header` is on.

We already re-direct `/meta-search` to `/external-sources`. `meta-search` should also redirect to the About page.

https://github.com/WordPress/openverse-frontend/blob/cc3f802c2d727417bfb2adb9f268e8739f9a1723/nuxt.config.ts#L244

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

### PR DESCRIPTION
**Pull request by anton202**
## Fixes

Fixes #1990  by @obulat 

## Description

This PR redirects /external-sources link to /about page. also removed external sources link from pop up menu in the old header

## Testing Instructions

* try navigating to /external-sources or /meta-search
* make sure that there is no external sources link in the pop up menu in the old header
external-sources

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [x] My pull request targets the *default* branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by anton202** [comment]
@obulat  oops, i did that in this #2000 PR. i`ll merge the changes to this branch as soon as the other PR will be merged

**Comment by anton202** [comment]
should be ready to merge

**Review by obulat — APPROVED** [review]
The redirect works, and the CI passes now ✨️

**Review by zackkrida — APPROVED** [review]
Nice!

**Pull request merged**
