### PR TITLE
Delete unused font files.

### LINKED ISSUE #1782: Delete unused font files
## Description

Openverse uses only one font for its interface, Inter. `src/assets/fonts` contains several other fonts we do not use. We should delete all of JetBrains Mono, Roboto, SourceSansPro font files.

### PR DESCRIPTION
**Pull request by CatherineNjenga**
## Fixes

Fixes #1782 by @obulat 
## Description

Deleted unused font files.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [x] My pull request targets the *default* branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [ ] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by obulat — CHANGES_REQUESTED** [review]
Thank you for creating your PR, @CatherineNjenga!
I forgot to mention in the issue that we will also need to remove the links to those fonts in the `fonts.css` file:
https://github.com/WordPress/openverse-frontend/blob/bf0c72e5ea660354e20ffa33a4caf0abd65a5db9/src/assets/fonts.css#L26-L45

These left-over links are causing the CI failures: the Nuxt app cannot be build because the linked files do not exist.

**Comment by CatherineNjenga** [comment]
Hello, @obulat, I have removed the links to the fonts in the fonts.css file.

**Review by obulat — CHANGES_REQUESTED** [review]
I'm really sorry, @CatherineNjenga. The CI tests show that we are, actually, using `JetBrains Mono` font in the attribution text area:
Screen Shot 2022-09-05 at 4 12 07 PM
So, we should put revert the last change to `fonts.css` and revert deleting JetBrainsMono font files.

**Comment by CatherineNjenga** [comment]
Hello, @obulat. Kindly guide me on the reverting process, I have tried to do the same from my end but has been unsuccessful.

**Comment by obulat** [comment]
Which code editor do you use?

**Comment by obulat** [comment]
I tried to create the instructions for VSCode, but I'm afraid that I have a couple of Git extensions, so it might be more confusing than useful. I normally use the WebStorm GUI for reverting, so I did that, and copied the commands that were run:
```
git revert 15d60a99f328c8f1b79b2dd0b6f47077cb610990
git revert 65c227a7d050ed2b572d229be8339f88e05d2659
git revert a51fadbc23e506e262ef118cd5a0bc83901617a1
git revert 5716b20d859c7ba118ab6a922c25b5b4372af411
git revert f462b890faebfbc4c5acfc67ca4a22c033a033a9
git revert d5284f0463cd15231bc9678320842fdc28e71f84
git revert 5c32a5e3c4d0b90845f046737510534fc37dbf0c
```
If you run them in order, it will first revert the commits that deleted the font files, and then revert the deletion inside the `font.css` file.
Let me know if you have any problems.

**Comment by CatherineNjenga** [comment]
Hello @obulat , I am unfortunately having issues cloning the repository locally.

**Review by obulat — APPROVED** [review]
Thank you for your contribution, @CatherineNjenga! I have updated the branch to only remove the unused fonts.
When you open a PR from your fork in the future, try to never commit to the `main` branch of your fork, and create a new branch for each PR instead. Otherwise, you will have problems when the two `main` branches (the upstream `main` and your fork's `main`) have different commits. Also, you will not be able to open two PRs at once. I have fallen into that trap several times when I was starting to contribute to open source projects :)

**Comment by CatherineNjenga** [comment]
Thank you, @obulat. You made my experience as a first-time contributor enjoyable and educative. I can't wait to be a regular contributor!

**Review by zackkrida — APPROVED** [review]
Great reduction to the size of the repo. LGTM!

**Pull request merged**
