### PR TITLE
Replace Search result page `h` element with a `p` element

### LINKED ISSUE #1615: Search result page should not have an h4
## Problem
The form with additional sources below the search result with the text 'Not finding what you're looking for...' should not be a heading. This is located in `VMetaSearchForm.vue` component:

Not finding what you're looking for screenshot

## Description
On the search result page (http://search.openverse.engineering/?q=cat), it is currently an h4. The visual styles should match the Figma mockups: [`md` and up](https://www.figma.com/file/w60dl1XPUvSaRncv1Utmnb/Audio-Release?node-id=1370%3A19752) and [mobile](https://www.figma.com/file/w60dl1XPUvSaRncv1Utmnb/Audio-Release?node-id=1393%3A20071).
Please, note that the current implementation still uses buttons and not a `select` for sources as in the mockup. That change will be implemented later.

### PR DESCRIPTION
**Pull request by Jbudd512**
## Fixes
Changed from h tag to p tag, and also changed the text styling.
Fixes #1615 by @obulat 

## Description
The search results message did not match the figma at all. Addresses issue with ticket #1615, where the search results message is styled as a header and not as a paragraph. Changed from h tag to p tag, and also changed the text styling.

## Checklist
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [x] My pull request targets the *default* branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by obulat** [comment]
Hi, @Jbudd512, thank you for your contribution! I will be reviewing this PR soon. Could you please edit the issue description and fill in the necessary information?

**Comment by kickeyhickey** [comment]
Hey @obulat ,
@rarne12 and I are working on this ticket with @Jbudd512 . We'll have that description up hopefully by the end of the day tomorrow for you.

**Comment by obulat** [comment]
@panchovm,
We are changing the meta search sentence at the bottom of the search page to be a paragraph, not a heading. I think it doesn't make sense to make it an `<h>` heading in accessibility terms. Until we convert the source buttons to a select, do the text styles in this screenshot look OK?
Screen Shot 2022-08-12 at 7 55 12 AM

**Comment by panchovm** [comment]
The text styles look good, but I encourage us to tackle #1197 and update the copy, styles, and how it works.

**Comment by obulat** [comment]
> The text styles look good, but I encourage us to tackle #1197 and update the copy, styles, and how it works.

Thank you for checking the PR and linking the other issue, @panchovm!

The main goal of this PR is to fix the accessibility problem caused by the headings not being in order. When Screen reader users navigate a site, they can do so using a document outline. And when there are missing levels (for example, if there is a `<h1>` and a `<h3>` heading, but no `<h2>`), it's not possible to do so. 
If you say that the text looks good, @panchovm, I believe it's a good solution for this a11y problem, and I will look into the issue you linked next week.

**Review by obulat — APPROVED** [review]
Thank you for your contribution, @Jbudd512, and welcome to Openverse! I am approving this PR, and it will be merged when you get 1 more approval by maintainers.

I've edited the description to link the issue it's solving, but I still hope you can write a short description of this PR.

**Comment by panchovm** [comment]
Absolutely @obulat 

I linked the issue to keep in mind the section relationship. It looks perfect to merge it as it is.

**Comment by Jbudd512** [comment]
@obulat Sorry for the delay, I've updated the original PR. Please let me know if you need anything else.

**Review by panchovm — COMMENTED** [review]
The three pieces of text, above and below the links list, would look better if they have the same style. I suggest using `Description regular`, found in the [Design Library](https://www.figma.com/file/GIIQ4sDbaToCfFQyKMvzr8/Openverse-Design-Library?node-id=311%3A331), and removing the font-weight value for these texts.

Similarly, the spacing above and below the links list would look better having a `32px` gap. 

Here is a screenshot of these changes applied on Firefox's inspector.

CleanShot 2022-08-15 at 10 40 45@2x

**Review by obulat — CHANGES_REQUESTED** [review]
Hi, @Jbudd512!
Here's a list of things that need to be done to make the section look like the screenshot above:
- line 5: remove the `mt-12` margin class
- line 9 and line 40: remove the `<header>` element: it's not necessary now that this section is not really a large one.
- between lines 9 and 40: remove `mb-2` class from the `<i18n>` elements so that the sentences don't have large gaps between them.
- line 32: add `text-base` class to the `<i18n>` element (this is the second sentence that you see in the form).
- line 43: Replace `mt-6 mb-10` with `my-8` so that the top and bottom margins of the buttons become balanced.

Please let me know if you have any questions or difficulties :)

**Comment by Jbudd512** [comment]
Thanks for the clarification @obulat! I believe we made the changes you suggested, and also applied a few more tailwind settings to match the Description Regular style (font-normal and leading-[130%]). Pushing the changes up now. Please let us know if these changes are sufficient.

CC: @RARNE12
CC: @kickeyhickey

**Review by obulat — APPROVED** [review]
The section and its code look really clean. Thank you for your contribution, @Jbudd512! 
Screen Shot 2022-08-18 at 6 14 56 PM

**Review by zackkrida — APPROVED** [review]

**Pull request merged**
