### PR TITLE
Use pnpm (and fix Storybook issues as a result)

### LINKED ISSUE #483: Storybook issues
## Description

The Storybook is not showing the stories written on `.mdx` files and the ability to change props with _knobs_ is not visible. I'm not sure with what changes this started to happen.

## Reproduction

1. Just run `npm run storybook`
2. Go to the open browser windows obverse there is not showing the index page
3. Search for the `VLicense` story for example and see it's not found neither

## Expectation

We want to show these stories too, using this format is especially important because it enables us to add documentation about the components.

## Screenshots

CleanShot 2021-12-03 at 16 50 49@2x

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

### PR DESCRIPTION
**Pull request by sarayourfriend**
## Fixes

Fixes #483 by @krysal 

## Description

Replaces `npm` with `pnpm`. `pnpm` has some significant advantages compared to `npm`, including super fast installs thanks to its local dependency cache. Dependencies are sym-linked into `node_modules` which makes using `pnpm` for many projects ultimately result in smaller disk usage. It also makes dependency re-installation super fast as it just has to create the sym-links. Similarly, deleting `node_modules` is much faster as you're just removing sym-links.

To support Vue we need to use the `shamefully-hoist` option as noted in this issue: https://github.com/pnpm/pnpm/issues/831 (note that the `shamefully-flatten` option has been renamed to `shamefully-hoist`)

Tagging @rbadillap specifically for review on this one as it touches the newly minted Dockerfile 🙂 

Marking this as high priority as not being able to properly use Storybook is not good for redesign development which we're currently moving quickly on.

## Testing Instructions

Checkout this branch and remove `node_modules` (for example `rm -rf node_modules`). Follow the instructions in the readme to install `pnpm` (`volta install pnpm`) then run `pnpm install`. Next run `pnpm storybook` and `pnpm dev` to ensure that they work 🎉 Also run `pnpm build` followed by `pnpm start`.

## Checklist

- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [ ] My pull request targets the *default* branch of the repository (`main`) or a parent feature branch.
- [ ] My commit messages follow [best practices][best_practices].
- [ ] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by zackkrida** [comment]
Oops, I actually pushed a commit with some config suggestions to your PR. Please review, as they're minor anyway!

Everything is working flawlessly for me, tested with:

> ✅ Installation and local run

```shell
rm -rf node_modules
volta install pnpm
pnpm i
npm run dev
```

> Docker run

```shell
docker compose up
```

> Storybook

```shell
pnpm run storybook
```

> Tests

```shell
pnpm run test:e2e
pnpm run test
```

**Comment by sarayourfriend** [comment]
@zackkrida just curious, why do we need to explicitly use `run` in docker?

**Comment by zackkrida** [comment]
@sarayourfriend We don't, I just think it's clearer for anyone checking, for example, documentation: 
https://pnpm.io/cli/run

I generally lean towards being verbose

**Comment by sarayourfriend** [comment]
Gotcha. I was following the style the recommend in their [`npm` equivalency table](https://pnpm.io/pnpm-cli#commands) where they exclude `run`

**Review by zackkrida — APPROVED** [review]
I'm fine with eliminating `run` usage @sarayourfriend, since the pnpm docs actively encourage _not_ writing out `run` it might actually be clearer without it. So glad this was such a win, and thanks for finding everywhere npm needed to be replaced 👍

**Review by obulat — APPROVED** [review]
I haven't tested the docker build but locally it is *amazingly* fast and Storybook mdx files all work for me. Thank you for improving devex, @sarayourfriend !

One small thing that isn't related but would reduce the number of warnings when running Storybook is to replace "license/VLicence" with "License/VLicense" (first letter is upper-case L).

**Comment by obulat** [comment]
Just a note: Webstorm integration with pnpm is not working great. I used the GUI (green 'run' triangles) to run the scripts from `package.json`, and now it's not working. Will have to use the command line more :)

**Comment by zackkrida** [comment]
@obulat Maybe these could help, it seems that it's _supposed_ to work!

https://stackoverflow.com/questions/63875255/how-to-set-up-pnpm-in-run-debug-in-webstorm
https://www.jetbrains.com/help/webstorm/installing-and-removing-external-software-using-node-package-manager.html

**Pull request merged**
