### PR TITLE
Update the language selector to work with the yellow pages

### LINKED ISSUE #1935: Language switcher should have a transparent background
## Problem

Currently, the language switcher is shown in the footer. When it is on the yellow background, it is white. It should be transparent, with a `dark-charcoal-20` border, instead

## Description

Change the `borderless` language chooser to be transparent.

## Additional context

Link to Figma 404 page: https://www.figma.com/file/KxkZmBNk218V2Fke1GeYCu/New-header-component?node-id=566%3A66902
Link to the component: https://www.figma.com/file/GIIQ4sDbaToCfFQyKMvzr8/Openverse-Design-Library?node-id=2960%3A8532
## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

### PR DESCRIPTION
**Pull request by dhruvkb**
## Fixes

Fixes #1935 by @obulat

## Description

This PR updates the language chooser to match the Figma mockups.

Screenshot 2022-10-25 at 8 32 14 PM

## Additional information
Since the dark charcoal 20% border involves some transparency the border color was not `border-dark-charcoal-20` but rather `#d6bb32`. On macOS, you can use the Digital Color Meter app to verify this by zooming in Figma and hovering over the border.

## Testing Instructions

- Visit http://localhost:8443/search/?q=cat&ff_new_header=on and see the language chooser in the footer.

image

- Visit http://localhost:8443/404/?ff_new_header=on and see the language chooser in the footer.

image

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [x] My pull request targets the *default* branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by obulat** [comment]
So quick and works great!
I would prefer to use the standart color even if it doesn't match the Figma mockup 100%. I wonder what @panchovm thinks...

One more nit: if we used 'transparent' color instead of 'yellow', we wouldn't have to change it in the future if the color scheme changes (maybe dark mode?)

**Comment by dhruvkb** [comment]
1. Using plain `border-dark-charcoal-20` makes the select field look quite bad and lacks contrast as it's a very light shade of gray on yellow.
2. Since the select field uses `#d6bb32` as the border color, we will need to update it if the color scheme changes from yellow to something else.

**Review by obulat — APPROVED** [review]
LGTM!

**Review by sarayourfriend — APPROVED** [review]
LGTM

**Comment by panchovm** [comment]
To @obulat's question, I think we should go with `border-dark-charcoal-20` instead of a specific color.

To @dhruvkb's points.

> Using plain border-dark-charcoal-20 makes the select field look quite bad

Something "looking quite bad" is not very useful feedback and relies on personal preferences.

The color style selected follows the transparency effect over white backgrounds. Here is a quick look at three variations over different backgrounds I am handling. Note that the dark version is still WIP.

CleanShot 2022-11-07 at 15 12 43@2x

The hit area does not need to meet the non-text contrast. The globe and dropdown icons surpass the 3:1 contrast ratio and indicate the actionable element. [See the 1.4.11 criterion](https://www.w3.org/WAI/WCAG21/Understanding/non-text-contrast.html).

> Since the select field uses #d6bb32 as the border color, we will need to update it if the color scheme changes from yellow to something else.

This is why I selected an opaque version that can shift to dark or white. And in the future, to a high contrast mode.

**Comment by obulat** [comment]
@panchovm, I believe Figma is handling colors a bit different than a browser does. If you set the border color to `dark-charcoal-20`, in the browser it looks more like silver than dark charcoal:

Screenshot 2022-11-14 at 2 30 23 PM

Do you think we should open a new issue to set the color to `dark-charcoal-20`, or should we just leave it as is. You can see the current version here: https://search-staging.openverse.engineering/nonexistentpage?ff_new_header=on

**Comment by panchovm** [comment]
That change makes sense.

> Are there many places where opacities are used?

Not really. I have pending the text style review, and it would be helpful to add this color revisit. But overall, most shades applied are from the solid set. Especially in text styles as opacities have i18n issues.

Thanks Olga for addressing the color update. I will update the Design Library to mirror Tailwind and avoid future mistakes.

**Pull request merged**
