### PR TITLE
Extract common functionality to useRecentSearches composable

### LINKED ISSUE #2047: Refactor recent searches to reduce code duplication
## Problem

Currently, we have two copies of the recent searches code: in mobile and desktop headers.

## Description

We should extract the handling of recent searches into a separate composable to reduce duplication.

## Implementation

- [x] 🙋 I would be interested in implementing this feature.

### PR DESCRIPTION
**Pull request by obulat**
## Fixes

Fixes #2047 by @obulat

## Description

This PR extracts common functionality for recentSearches handling into a composable. It is reused in `VHeaderMobile` and `VSearchBar` (which is used by the `VHeaderDesktop`).

## Testing Instructions

The recent searches feature in the new header should work as normal.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [x] My pull request targets the *default* branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [ ] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by zackkrida — CHANGES_REQUESTED** [review]
The implementation looks nice, however I have observed a difference between this PR and `main`. This PR breaks closing the recent searches when tabbing backwards out of the search bar.

**Comment by obulat** [comment]
> The implementation looks nice, however I have observed a difference between this PR and `main`. This PR breaks closing the recent searches when tabbing backwards out of the search bar.

Thank you for catching this! It turns out that this is more complicated than I initially thought because some keydown events that are handled by the input on desktop need to be handled by the modal on mobile. I'm going to draft this PR until I fix it.

**Comment by krysal** [comment]
@obulat Do you think this work can be resumed this week or should we close it?

**Comment by obulat** [comment]
I am going to close this PR because fixing some interactions in the modal/input require more work, and I don't have the capacity at the moment.

**Pull request closed without merging**
