### PR TITLE
Update the WordPress logo in the footer

### PR DESCRIPTION
**Pull request by dhruvkb**
## Fixes

Related to #1433 by @panchovm 

## Description

This PR updates the "(W) WordPress" logo in the footer with the simplified "(W)" logo. I didn't realise that so many snapshots would be updated by this change.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like
      `Update index.md`).
- [x] My pull request targets the _default_ branch of the repository (`main`) or
      a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible
      errors.

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by dhruvkb** [comment]
Blocking to allow other changes to the homepage to be merged. Since it contains visual regression snapshots, the PR needs to updated on top of `main` before merging.

**Review by obulat — APPROVED** [review]
Great! Thank you for updating the spacings, too.

**Comment by panchovm** [comment]
It looks great ✨

**Comment by obulat** [comment]
@dhruvkb, I think we should merge it now instead of blocking on other changes. This way, all of the other PRs will rebase onto this, and have the updated snapshots. Otherwise, we'll have to re-base several times.
Also, for the same reasons (so as not to update the snapshots several times), I added this change to https://github.com/WordPress/openverse-frontend/pull/2051 before updating its snapshots.

**Comment by dhruvkb** [comment]
@obulat should I merge with a single approval? It's not a very risky change so if you agree, I'll merge it.

**Comment by dhruvkb** [comment]
Merging considering @panchovm's comment as an approval.

**Pull request merged**
