### PR TITLE
Add small dropdown button variant

### LINKED ISSUE #510: Add smaller size for Download button
## Problem

The 'Full size S' layout for the Audio track users a smaller download button (40px height) as compared to the one used in 'Full size M' (53px height).

The Download button currently does not offer this size.

## Description

The `DownloadButton` component, which inherits from the `DropdownButton` component should provide two size configurations to choose from, the existing bigger size and the new smaller size.

## Additional context

Figma node: https://www.figma.com/file/GIIQ4sDbaToCfFQyKMvzr8/Openverse-Design-Library?node-id=1029%3A5890

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

### PR DESCRIPTION
**Pull request by sarayourfriend**
## Fixes

Fixes #510 by @dhruvkb 

## Description

Adds a small size dropdown button option in the most ad-hoc way possible... but it does work for now. In the future it'd be nice to refactor it top-down to use our VButton and other standard components, but it's not possible to do in the amount of time we have right now.

## Testing Instructions

Checkout this branch and run `pnpm storybook` and visit the [dropdown button story](http://localhost:6006/?path=/story/components-dropdownbutton--default) and toggle between the medium and small size props.

Also check out the [small audio track component story](http://localhost:6006/?path=/story/components-audio-track--full-small) and verify that the download button is the same height as the play/pause button.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [x] My pull request targets the *default* branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [N/A] I added or updated tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by sarayourfriend** [comment]
I just noticed I accidentally also included the VButtonGroup component. Should I just leave this in? Or [YAGNI](https://en.wikipedia.org/wiki/You_aren't_gonna_need_it) it for another day when we can finally refactor everything to use VButton?

**Review by zackkrida — APPROVED** [review]
YAGNI
LGTM
TY

Seriously though, I still like the approach you took to the size class and the heavy commenting on this 'hack'. Nice!

**Review by krysal — APPROVED** [review]
Nice, the size adjustment looks good! A curious thing is that it does not show rounded edges on the right in LTR mode when there is no dropdown menu, even though in RTL it looks perfectly rounded. I noticed this in the Audio Track Full [[Medium](http://localhost:6006/?path=/story/components-audio-track--full-medium)/[Small](http://localhost:6006/?path=/story/components-audio-track--full-small)] story.

**Comment by sarayourfriend** [comment]
@krysal that is strange, thank you for noticing that! I think it's a bug with the rtl plugin. I'll merge this and we can fix that soon in a separate PR.

**Pull request merged**
