### PR TITLE
Add VContentSettingsButton

### LINKED ISSUE #1805: Component: VContentSettings IconButton
_All work for the 'Create new header' milestone should be done under the `new_header` feature flag._

## Description

The new header component has a Content settings Icon Button for selecting content types (audio/images/all) and filters on screens below `md` breakpoints.

### Props

| Name | Type | Description |
|-|-|-|
| isPressed | Boolean | Whether the button has been pressed (activated). When it is pressed, its colors are inverted, and the background is dark charcoal |
| areFiltersSelected | Boolean | Whether some filters have been selected. It should show a pink dot in the top right corner.

### Data and computeds
It should accept the following attrs to pass them on to the underlying button component.

| Name | Type | Description |
|-|-|-|
| aria-label | String | Translated name of the button to be used as accessible name | 
| aria-pressed | Boolean | Based on the `isPressed` prop.
| aria-controls | String | The id of the element it controls. It should be the modal on mobile; can be left blank until we implement the new mobile modals. Should have a default (as it would probably have a single value in prod)

### Events

| Name | Associated data | Description |
|-|-|-|
| click | - | The click event

## Code samples

```vue
<VContentSettingsButton
  :is-pressed="false"
  :are-filters-selected="true"
>
</VContentSettingsButton>
```
## Dependencies

`VIconButton`
The `settings` SVG from the Figma file.

## References

- **Figma:** https://www.figma.com/file/KxkZmBNk218V2Fke1GeYCu/New-header-component?node-id=522%3A59429

## Implementation

- [ ] 🙋 I would be interested in implementing this component.

### PR DESCRIPTION
**Pull request by obulat**
## Fixes

Fixes #1805 by @obulat

## Description

This PR adds the `VContentSettingsButton` for the mobile version of the new header.

## Testing Instructions

Run the Storybook (`pnpm storybook`) and check `VHeader`/`VContentSettingsButton`. Check that the `pressed` and `areFiltersSelected` variants match the mockups: https://www.figma.com/file/KxkZmBNk218V2Fke1GeYCu/New-header-component?node-id=522%3A59429

## Checklist

- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [ ] My pull request targets the *default* branch of the repository (`main`) or a parent feature branch.
- [ ] My commit messages follow [best practices][best_practices].
- [ ] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by zackkrida — APPROVED** [review]
It's pixel-perfect, LGTM! One question: Should we make the `pressed` style _also_ applied on focus and hover, for instances where the user is using a narrow desktop window? It's an edge case and not essential but might be nice.

**Comment by obulat** [comment]
We should add `aria-label` to the notification dot so that screen reader users are also notified about its existence.

**Review by dhruvkb — APPROVED** [review]
Looks perfectly fine to me. 100% correspondence with the mockups.

**Comment by obulat** [comment]
> One question: Should we make the `pressed` style _also_ applied on focus and hover, for instances where the user is using a narrow desktop window? It's an edge case and not essential but might be nice.

I'm not sure about that because for other buttons, `pressed` style is pretty distinct, and the focus/hover styles used a different style. I can open a design issue for this.

**Pull request merged**
