### PR TITLE
Fix stories for `VContentLink` and `VSearchTypePopover`

### LINKED ISSUE #1135: Lots of stories broken in Canvas view
## Description
Many stories in the Storybook on `main` are broken. This might be a consequence of updating it to Storybook 6.4 although there are no breaking changes in the changelog. Strangely enough, the smoke test passes.

## Reproduction

Visit the ["Components/VAudioThumbnail/Square" story](https://wordpress.github.io/openverse-frontend/?path=/story/components-vaudiothumbnail--square) in the "Canvas" view. There might be other stories broken in a similar fashion.

## Expectation

The stories should render.

## Additional context

The broken stories can be fixed by using the composition API format with a `setup()` function. See #1134 which fixes the stories for  "Components/VLicense".

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

### PR DESCRIPTION
**Pull request by dhruvkb**
## Fixes

Fixes #1135 by @dhruvkb 

## Description

This PR fixes two stories
- `VContentLink` which is broken in the UI
- `VSearchTypePopover` which has the wrong file name

## Testing Instructions

0. Checkout the branch and run the Storybook.
1. Check that the story for `VContentLink` works (which it doesn't on `main`).
2. Check that the file name for the `VSearchTypePopover` story matches the component name.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [x] My pull request targets the *default* branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by dhruvkb** [comment]
Why is the Nuxt app build size changing when stories are modified 🤔?

**Comment by sarayourfriend** [comment]
Not sure why, but it is concerning that a noop (from nuxt's perspective) is causing an increase.

**Review by sarayourfriend — APPROVED** [review]

**Review by krysal — APPROVED** [review]
Nice!

**Comment by krysal** [comment]
@dhruvkb I noticed the **VPopover / Control** story is broken, not sure if it's a problem with the component, do you want to include it here? We can create another ticket for that any time of course.

**Comment by sarayourfriend** [comment]
You can see it here: https://wordpress.github.io/openverse-frontend/1383/?path=/story/components-vpopover--control

If you open the popover and then click outside of the popover to closes it will crash on `element.focus` is not a function.

I suspect this is probably an error in the dialog composables, not with the story though.

Is that what you were talking about @krysal ?

**Comment by krysal** [comment]
That's correct @sarayourfriend, I forgot to mention it's the interaction with the popover that is broken.

**Comment by dhruvkb** [comment]
If it's not a story issue, I'll merge this PR.

**Pull request merged**
