### PR TITLE
Add stop-gap solution for e2es

### PR DESCRIPTION
**Pull request by sarayourfriend**
## Fixes

Part of #554 by @sarayourfriend 

## Description

Adds a step to run the e2e suite in the CI workflow. This isn't the ideal situation as it doesn't actually replicate the production environment because it doesn't have the wp.org wrapper. We can continue to explore a solution that accomodates that but for now this is better than nothing.

## Testing Instructions

Let the CI run and verify that it works.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [x] My pull request targets the *default* branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [N/A] I added or updated tests for the changes I made (if applicable).
- [N/A] I added or updated documentation (if applicable).
- [N/A] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by obulat** [comment]
The tests are failing because I added a really hacky test for 'Meta search' sources. It checks for the number of buttons, and it wasn't updated when a new image source was added recently. So, it returns 6 instead of the previously-correct value of 5.

Also, I wonder if it's a good idea to merge this before adding the SSR mocking. Currently, we only mock the network requests on Client-side rendering, and anything rendered on the Server-side goes through the actual server, which takes a long time, and is flaky.

**Comment by sarayourfriend** [comment]
The tests currently fail also fail for me locally.

**Comment by sarayourfriend** [comment]
> Also, I wonder if it's a good idea to merge this before adding the SSR mocking. Currently, we only mock the network requests on Client-side rendering, and anything rendered on the Server-side goes through the actual server, which takes a long time, and is flaky.

Ah, good point. We should do the mocking for the server side as well 😕

**Comment by sarayourfriend** [comment]
@obulat what do you think about us merging this as is for now and then opening another issue to investigate how to get Audio passing consistently (while also relying only on text on the screen that users will be able to interact with?)

**Comment by obulat** [comment]
I agree, @sarayourfriend

**Review by obulat — APPROVED** [review]

**Review by dhruvkb — APPROVED** [review]

**Pull request merged**
