### PR TITLE
Use v-show instead of v-if for width-based condition

### LINKED ISSUE #882: SSR Audio results page crashes
## Description

The audio results page when loaded from SSR crashes every time: https://search-staging.openverse.engineering/search/audio?q=birds

## Reproduction

1.  Go to https://search-staging.openverse.engineering/search/audio?q=birds
2.  Open console and see errors. Note page is non-interactive.

## Expectation

It shouldn't crash.

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

### PR DESCRIPTION
**Pull request by obulat**
## Fixes

Fixes #882 by @sarayourfriend

## Description

This PR does two things:
- replace `v-show` directives with a condition based on width(`isSmall`) with `v-if` to ensure that the server-rendered markup matches the client-rendered markup. I'm not sure that this is the best solution for all of these places, but it fixes the warnings.
- Replace the helpText options api based computed with a composition api based computed. I'm not sure it's needed, but I added it because the warning specifically was about `t` not being defined (I guess it's `i18n` `$t`?)

## Testing Instructions

Open the audio search page by going to http://localhost:8443/search/audio?q=bird on a desktop and look at the console. It should not display any warnings. 

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [x] My pull request targets the *default* branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by sarayourfriend — DISMISSED** [review]
LGTM. Tested locally by changing the screen width and reloading the page various times. Tested in mobile safari as well, both SSR and also client side rendering.

Not sure if the i18n change is necessary either but it doesn't seem to hurt. I suspect the error about `t` being undefined is a red herring and refers to some Vue internal minified utility rather than something actually named `t`.

**Comment by sarayourfriend** [comment]
@WordPress/openverse-developers Can this get another review? The related issue is critical (SSR audio page crashes) and would be nice to fix before we deploy the new version of the frontend now that the wporg theme is updated.

**Review by krysal — COMMENTED** [review]
I'm not seeing all the waveforms when SSR.

Also, we should probably add some E2E tests here.

CleanShot 2022-02-22 at 12 23 07@2x

**Comment by sarayourfriend** [comment]
I see the same locally @krysal. I can't find a reason for it though :confused:

**Comment by obulat** [comment]
Thank you for catching this, @krysal ! 
It was rendering the 'small' layout that doesn't have waveform and controller on SSR, because by default on the server we set the size to mobile. I've added the check for user agent to layout calculation, and set it to `s` only for mobile user agents.

**Review by zackkrida — APPROVED** [review]
This looks good to me! Not seeing any cross-browser issues and seeing the correct layouts on mobile and desktop.

**Review by sarayourfriend — APPROVED** [review]

**Review by krysal — APPROVED** [review]
Works well now!

**Pull request merged**
