### PR TITLE
Add a directive for translators to not translate Netherlands

### LINKED ISSUE #2189: Add translator note for Dutch translation of `search-guide.example.prefix.content`
We should include a notice for translators for this string `search-guide.example.prefix.content`, because translating "Netherlands" could remove the prefix used to explain this search syntax.

From a commenter in Slack:

>  I just wanted to say that for this string: https://translate.wordpress.org/projects/meta/openverse/nl/default/?filters%5Bstatus%5D=[…]inal_id%5D=12384661&filters%5Btranslation_id%5D=100956682 I'd add an additional comment so that it's clear that they don't translate the whole string for batum since e.g. Netherlands in Dutch is Nederland. Which wouldn't be correct with "Net" in the previous sentence of the string.

### PR DESCRIPTION
**Pull request by dhruvkb**
## Fixes

Fixes #2189 by @zackkrida

## Description

Add a note for translators to not translate 'network', 'Netflix' and 'Netherlands', which are used as examples of words starting with 'net'. If translated to these would no longer be valid examples.

## Alternative

An alternative approach would be to pick a different triplet of words in each language but that would be too cumbersome and wouldn't accurately reflect the English-centric nature of the Openverse search engine.

## Testing Instructions

Test that the POT contains the comment.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like
      `Update index.md`).
- [x] My pull request targets the _default_ branch of the repository (`main`) or
      a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible
      errors.

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by zackkrida — APPROVED** [review]
That was quick, thanks!

**Review by krysal — COMMENTED** [review]
Instead of adding the comment, why not to exclude those words for translations entirely and prevent that from happening?

**Comment by dhruvkb** [comment]
@krysal do you mean by adding ESLint rules to ignore them and use raw text?

**Review by obulat — APPROVED** [review]
I liked @krysal's suggestion at first, but then thought that if we ever add those words to the main site text, it would be affected, too. So, I prefer this fix instead.

**Comment by krysal** [comment]
Sorry for responding late. I wasn't thinking of excluding these words globally, just for the Search Help page. I send a PR with the fix in #2194.

**Pull request merged**
