### PR TITLE
Image cell focus state improvements

### LINKED ISSUE #1004: Image results lack a focus state
## Description

The image search endpoint: https://search-staging.openverse.engineering/search/image?q=dogs does not have any focus state on the single image results.

## Expectation

These images should have the same focus state as images in the 'all results' view.

### PR DESCRIPTION
**Pull request by zackkrida**
## Fixes

Fixes #1004 by @zackkrida 

## Description

This PR makes several improvements to the ImageCell component:

- Adds a pink focus ring
- Unifies the hover/focus state that shows the CC license icons
- Renames to `VImageCell`. The existing `VImageCell` in the `VAllResults` grid is reamed to `VImageCellSquare`.
- Removes unnecessary custom styles
- Removes the unused `shouldContainImage` prop
- Gives the license icons the correct color in the production build
- Updates the gap between images in the VImageGrid to match the VAllResults grid

This PR also makes it quite evident that we should be able to unify the two image cell components, with an `aspect-ratio` prop for switching between square and aspect ratio appearances. The differences should be pretty straightforward to extract into a composable and some conditional logic in the template; I'll create a new issue for that as well.

Finally, this PR adds an offset to the BoxAudio focus ring, to match the ImageCell components.

## Screenshots

CleanShot 2022-02-25 at 10 47 37@2x

CleanShot 2022-02-25 at 10 47 48@2x

## Testing Instructions

- `pnpm build && pnpm start`, then bavigate through the All results and image views via keyboard. Observe:
  - Correct focus states for  images and boxed audio
  - Correct icon color
- Look at related images and verify correct styles there too.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [x] My pull request targets the *default* branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added or updated tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by panchovm — DISMISSED** [review]
I noticed two things following:

### Focus ring styles
The focus style has two borders, an internal white border of `3px` and an external pink border of `3px`. This definition follows the [Media focus style exploration](https://github.com/WordPress/pattern-directory/pull/375#issuecomment-981894463).

#### Mockup
CleanShot 2022-02-25 at 14 08 37@2x

Here you can see that white border is inside the image area

### Padding in license set
Padding should be `8px` instead of `4px`.

CleanShot 2022-02-25 at 14 01 58@2x

**Comment by sarayourfriend** [comment]
LGTM from a technical perspective. Tested on FF on Linux and Chromium and Chrome on Windows. Can someone confirm a test in Safari?

**Comment by zackkrida** [comment]
@panchovm updated the size!

CleanShot 2022-02-25 at 13 38 57@2x
CleanShot 2022-02-25 at 13 38 16@2x
CleanShot 2022-02-25 at 13 37 48@2x

@sarayourfriend I noticed that on search-staging.openverse.engineering and localhost, I can't even _tab_ through image results 😬! On all results, it skips to tabbing between the audio items. On the image only grid it jumps straight to the load more button. 

Since that doesn't relate to this PR, I'll make a new issue ASAP. 

Edit: Actually, it's safari in-general, not specifically voiceover!

**Comment by zackkrida** [comment]
Ah, okay, when I enable `Preferences > Advanced > Press tab to highlight each item on a page"` in Safari, it reads the image titles perfectly!

**Comment by sarayourfriend** [comment]
Unfortunately on macOS you have to enable a few different settings to get the OS to behave as expected for keyboard navigation :confused:

**Comment by sarayourfriend** [comment]
> should we add a tabindex to all of our links then?

If we can make the site work as expected without having to rely on users enabling OS level preferences (aside from the basic "use keyboard navigation" one that is disabled by default) that would be ideal. Please do create another issue for that if you think it's possible.

**Comment by zackkrida** [comment]
@WordPress/openverse-frontend if folks can review this Monday, I think it would be good to merge prior to the deploy, since it fixes an accessibility problem.

**Review by sarayourfriend — APPROVED** [review]
LGTM, tested in Firefox and Chromium on Linux. If someone could test and confirm in Safari that'd be great.

**Comment by panchovm** [comment]
It looks great on desktop and mobile. 

A nitpicky comment. The internal border goes inside the image area, masking it with its `3px` white border. As seen in the horizontal and vertical rules of [this image](https://user-images.githubusercontent.com/895819/155757342-903b2d09-9ef8-4388-bf63-81878394be79.png).

However, the comment above should not block its merge, and we can make the change in the future.

**Review by panchovm — APPROVED** [review]

**Pull request merged**
