### PR TITLE
Update tailwindcss-rtl, talkback and typescript

### LINKED ISSUE #1086: Outdated dependencies
## Description

Keeping packages updated should help us make an easier transition to Nuxt 3. There are several with major versions behind so this will require multiple PR to make sure each update does not break the app. It is suggested to start by devDependencies. 

### Production dependencies
<details>
<summary>
`pnpm outdated -P --no-table`</summary>

```
build-url
6.0.1 => Deprecated

@nuxtjs/sentry
5.1.6 => 5.1.7

clipboard
2.0.8 => 2.0.10

filesize
8.0.6 => 8.0.7

focus-trap
6.7.1 => 6.7.3

postcss-focus-visible
6.0.3 => 6.0.4

@babel/eslint-parser
7.16.5 => 7.17.0

core-js
3.19.3 => 3.21.1

node-html-parser
5.1.0 => 5.2.0

js-cookie
2.2.1 => 3.0.1

vue-i18n
8.26.7 => 9.1.9

@nuxtjs/composition-api
0.27.0 => 0.32.0

@nuxtjs/svg
0.3.0 => 0.4.0

axios
0.21.4 => 0.26.1
```
</details>

### Development dependencies
<details>
<summary>
`pnpm outdated -D --no-table`</summary>

```
eslint-loader (dev)
missing (wanted 4.0.2) => Deprecated

@testing-library/jest-dom (dev)
5.16.1 => 5.16.2

autoprefixer (dev)
10.4.0 => 10.4.2

postcss (dev)
8.4.5 => 8.4.8

tailwindcss (dev)
3.0.9 => 3.0.23

@babel/runtime-corejs3 (dev)
7.16.5 => 7.17.2

@nuxtjs/storybook (dev)
4.2.0 => 4.3.0

@playwright/test (dev)
1.17.1 => 1.19.2

@typescript-eslint/eslint-plugin (dev)
5.12.0 => 5.14.0

@typescript-eslint/parser (dev)
5.12.0 => 5.14.0

eslint-config-prettier (dev)
8.3.0 => 8.5.0

sass (dev)
1.45.0 => 1.49.9

ts-node (dev)
10.5.0 => 10.7.0

typescript (dev)
4.5.5 => 4.6.2

@testing-library/vue (dev)
5.8.2 => 6.5.1

@types/jest (dev)
26.0.24 => 27.4.1

babel-jest (dev)
26.6.3 => 27.5.1

eslint (dev)
7.32.0 => 8.10.0

eslint-plugin-prettier (dev)
3.4.1 => 4.0.0

eslint-plugin-unicorn (dev)
35.0.0 => 41.0.0

eslint-plugin-vue (dev)
7.20.0 => 8.5.0

jest (dev)
26.6.3 => 27.5.1

lint-staged (dev)
11.2.6 => 12.3.5

sass-loader (dev)
10.2.0 => 12.6.0

@intlify/eslint-plugin-vue-i18n (dev)
0.11.1 => 1.4.0

@vue/test-utils (dev)
1.3.0 => 2.0.0-rc.17

eslint-plugin-vuejs-accessibility (dev)
1.1.1 (wanted 0.6.2) => 1.1.1

tailwindcss-rtl (dev)
0.8.0 => 0.9.0
```
</details>

## Expectation

A `package.json` with dependencies up to date whenever possible.

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

### PR DESCRIPTION
**Pull request by kb-0311**
## Fixes

Related to #1086 by @krysal 

## Description

Just started with updating dev dependencies related to #1116 
## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [x] My pull request targets the *default* branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added or updated tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by sarayourfriend** [comment]
It looks like sass-loader has some compatibility issues :disappointed: Can you revert the update to sass-loader for this PR but leave the rest? We're planning to remove the Sass dependencies entirely in #1096 so we'll be able to remove those dependencies soon anyway.

**Comment by kb-0311** [comment]
yeah no problem , on It.

**Comment by kb-0311** [comment]
@sarayourfriend I hope it is good to go now.

**Review by sarayourfriend — APPROVED** [review]
LGTM! For good measure I smoke tested Storybook and everything appears to be working :tada:

**Review by krysal — APPROVED** [review]
Nice, thanks for your help @kb-0311!

**Pull request merged**
