### PR TITLE
Move the sidebar in the DOM order

### LINKED ISSUE #2125: Keyboard navigation to the footer on the search page is impossible
## Description

If you try to navigate the site using the keyboard <kbd>Tab</kbd>, you will not be able to get to the footer. After the last element in `main`, your focus goes to the beginning (header).

## Reproduction

1. Navigate through the search results using the <kbd>Tab</kbd> key.
2. After passing the external search form, you will see that you land on the header.

## Screenshots

Kapture  2023-02-02 at 08 13 07

## Additional context

The intention behind the focus management is to allow the user to navigate to the filters sidebar after passing the filters button, instead of going through all of the search results (the natural order). This is the composable that handles it: https://github.com/WordPress/openverse-frontend/blob/main/src/composables/use-focus-filters.ts
We need to move the point of where the focus is moved back to the beginning of the site from the end of "main" to the end of "footer".

### LINKED ISSUE #2182: Expanding the filters sidebar does not focus a screen reader on the filters section
## Problem
The desktop version of the search page has an expandable filters sidebar on the right. When the user opens the sidebar by clicking on the "Filters" button, the page focus should move to the sidebar. We have implemented this for the keyboard "tabbing" order. However, this does not help the screenreaders: they follow the DOM order (i.e., the order in which the elements are written in the code)

## Possible Solutions
We could move the sidebar to the left side of the screen.
Another possible solution to try could be to use the "filters sidebar" -> "main content" order in the DOM, but switch it using CSS. Normally, using CSS for ordering is bad for accessibility, but here it would probably have an opposite effect. 

## Original description by @alexstine
Expanding the Filters button does not focus the user in the filtering section. Adjust the DOM order so the filtering options appear directly after the Filter button.

### PR DESCRIPTION
**Pull request by obulat**
## Fixes

Fixes #2125 by @obulat
Fixes #2182 by @obulat

## Description

This PR moves the sidebar in the DOM order to the position right after the header. Then, using CSS grid, the visual order is changed back to "sidebar on the right". This way, the focus order for keyboard users and for screenreader users is Header -> Filters sidebar -> Main -> Footer.

Normally, using CSS to change the DOM order is bad, but in the case of the search page layout, this actually converts the DOM order into the expected one. 

Previously, we used code to manually handle focus after "Tab"/"Shift+Tab" presses on "Filters" button and the last tabbable element in the sidebar and `main` content. However, this only worked for the keyboard navigation, and not the screenreader navigation. 
This PR allows us to remove the manual focus management code.

### Before
Screenshot 2023-02-15 at 8 58 34 AM

### After LTR

Screenshot 2023-02-15 at 9 07 03 AM

### After RTL

Screenshot 2023-02-15 at 5 30 23 PM

## Testing Instructions

Open the search page. Move focus using your keyboard "Tab" key: after the Filters 

## Checklist

- [x] My pull request has a descriptive title (not a vague title like
      `Update index.md`).
- [x] My pull request targets the _default_ branch of the repository (`main`) or
      a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible
      errors.

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by dhruvkb** [comment]
@obulat how did you generate the tab-order image? Can you also share what the tab-order looks like for RTL languages?

**Comment by zackkrida** [comment]
@dhruvkb it's a firefox feature!

CleanShot 2023-02-15 at 09 11 33

**Review by dhruvkb — APPROVED** [review]
This is a good way to avoid the need to control focus with JS. Appreciate all the code that we could delete.

**Review by zackkrida — APPROVED** [review]
Really great!

**Pull request merged**
