### PR TITLE
Fix narrow width audio results

### LINKED ISSUE #1278: Mobile audio results using incorrect audio track layout
## Description

The audio results isn't switching to the correct track layout on small displays.

## Reproduction

1. View https://wordpress.org/openverse/search/audio?q=dog on a mobile device
2. Observe incorrect audio layout

## Screenshots

CleanShot 2022-04-14 at 20 42 17@2x

## Environment

 - Device: 
 - OS: 
 - Browser: 
 - Version: 
 - Other info: 

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

### PR DESCRIPTION
**Pull request by sarayourfriend**
## Fixes

Fixes #1278  by @zackkrida 

## Description

The fix in this PR is actually just two lines, flipping one boolean and switching an and to an or.

The rest is all tests and test support.

## Testing Instructions

Checkout the snapshots and also run the app locally by checking out the branch and running `pnpm dev`. Visit the audio results page, both via client side navigation and via SSR with and without a mobile UA and verify that the correct layout and size is used for every situation. The snapshots should help with that as well.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [x] My pull request targets the *default* branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added or updated tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by zackkrida — APPROVED** [review]
This is wonderful! Some of the screenshots show some xs screen horizontal cropping but we can look at that outside of this PR.

**Review by obulat — COMMENTED** [review]
On a narrow desktop view, the SSR-ed page is still displaying incorrect layout: there is a large play-pause button on the right side, and the little play-pause button is lower than it should be (it's actually outside of the thumbnail). If you open the same page on the client, it looks correct.
Sometimes, when you use a computed on SSR, it doesn't get re-evaluted on the server. Using conditional `hidden` class on the server to hide something can also not be updated on the server, and the element can stayl visible. I'm not sure why or when it occurs, but I had a lot of trouble debugging a conditional class not being applied on the server render when working on the filters button label.

I tried replacing `audioTrackSize` computed with a `ref`, `watch` and `onMounted`:
```
    // On SSR, we set the size to small if the User Agent is mobile, otherwise we set the size to medium.
    const isMobile = ref(useBrowserIsMobile())
    const updateAudioTrackSize = () => !isMinScreenMd.value || isMobile ? 's' : props.isFilterVisible ? 'l' : 'm'

    const audioTrackSize = ref(updateAudioTrackSize())

    onMounted(() => {
      audioTrackSize.value = updateAudioTrackSize()
    })

    watch(
      [isMinScreenMd, isMobile, props],
      ([isMinScreenMd, isMobile, isFilterVisible]) => {
        updateAudioTrackSize()
      }
    )
```

It seems to fix the layout on narrow computer screen, at least after the component is mounted.

**Comment by sarayourfriend** [comment]
@obulat Interesting, I didn't notice that.

Using `onMounted` in the audio track doesn't seem to change anything, indeed, if you check the props being passed it is passing the correct size to the layout component (`s` in this case). It appears to be some kind of issue where the layout isn't re-rendering even though the prop value changes.

This commit (https://github.com/WordPress/openverse-frontend/pull/1281/commits/d5a965632a56c2bb974da8054b4336ae6dca0edd) fixed it :shrug:

**Review by krysal — APPROVED** [review]
LGTM! I see the audio player layout changing and no regressions 👍

**Pull request merged**
