### PR TITLE
updated dependencies

### LINKED ISSUE #1086: Outdated dependencies
## Description

Keeping packages updated should help us make an easier transition to Nuxt 3. There are several with major versions behind so this will require multiple PR to make sure each update does not break the app. It is suggested to start by devDependencies. 

### Production dependencies
<details>
<summary>
`pnpm outdated -P --no-table`</summary>

```
build-url
6.0.1 => Deprecated

@nuxtjs/sentry
5.1.6 => 5.1.7

clipboard
2.0.8 => 2.0.10

filesize
8.0.6 => 8.0.7

focus-trap
6.7.1 => 6.7.3

postcss-focus-visible
6.0.3 => 6.0.4

@babel/eslint-parser
7.16.5 => 7.17.0

core-js
3.19.3 => 3.21.1

node-html-parser
5.1.0 => 5.2.0

js-cookie
2.2.1 => 3.0.1

vue-i18n
8.26.7 => 9.1.9

@nuxtjs/composition-api
0.27.0 => 0.32.0

@nuxtjs/svg
0.3.0 => 0.4.0

axios
0.21.4 => 0.26.1
```
</details>

### Development dependencies
<details>
<summary>
`pnpm outdated -D --no-table`</summary>

```
eslint-loader (dev)
missing (wanted 4.0.2) => Deprecated

@testing-library/jest-dom (dev)
5.16.1 => 5.16.2

autoprefixer (dev)
10.4.0 => 10.4.2

postcss (dev)
8.4.5 => 8.4.8

tailwindcss (dev)
3.0.9 => 3.0.23

@babel/runtime-corejs3 (dev)
7.16.5 => 7.17.2

@nuxtjs/storybook (dev)
4.2.0 => 4.3.0

@playwright/test (dev)
1.17.1 => 1.19.2

@typescript-eslint/eslint-plugin (dev)
5.12.0 => 5.14.0

@typescript-eslint/parser (dev)
5.12.0 => 5.14.0

eslint-config-prettier (dev)
8.3.0 => 8.5.0

sass (dev)
1.45.0 => 1.49.9

ts-node (dev)
10.5.0 => 10.7.0

typescript (dev)
4.5.5 => 4.6.2

@testing-library/vue (dev)
5.8.2 => 6.5.1

@types/jest (dev)
26.0.24 => 27.4.1

babel-jest (dev)
26.6.3 => 27.5.1

eslint (dev)
7.32.0 => 8.10.0

eslint-plugin-prettier (dev)
3.4.1 => 4.0.0

eslint-plugin-unicorn (dev)
35.0.0 => 41.0.0

eslint-plugin-vue (dev)
7.20.0 => 8.5.0

jest (dev)
26.6.3 => 27.5.1

lint-staged (dev)
11.2.6 => 12.3.5

sass-loader (dev)
10.2.0 => 12.6.0

@intlify/eslint-plugin-vue-i18n (dev)
0.11.1 => 1.4.0

@vue/test-utils (dev)
1.3.0 => 2.0.0-rc.17

eslint-plugin-vuejs-accessibility (dev)
1.1.1 (wanted 0.6.2) => 1.1.1

tailwindcss-rtl (dev)
0.8.0 => 0.9.0
```
</details>

## Expectation

A `package.json` with dependencies up to date whenever possible.

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

### PR DESCRIPTION
**Pull request by kb-0311**
## Fixes

Fixes #1086 by @krysal 
## Description

Update the dependencies in the package.json
## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [x] My pull request targets the *default* branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added or updated tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by kb-0311** [comment]
can someone please add the labels for me?

**Comment by sarayourfriend** [comment]
@kb-0311 Couple of things here:

1. For updating dependencies we also need to generate a new `pnpm-lock.yaml`. This should automatically happen when you run `pnpm install` after updating any dependency versions in `package.json`.
2. If you check out the issue @krysal added a note about us not wanting to update all the dependencies in one go, in particular not the runtime dependencies. If you could change the PR to only update the development dependencies or else just one dependency in package.json that'd be great :+1: 

Thanks for the contributions you've been making, we really appreciate it!

**Comment by kb-0311** [comment]
@sarayourfriend 
ohh ok cool I will just update only the dev dependencies . 

I have actually learned a lot from OS contribution so the pleasure is all mine : )

**Comment by kb-0311** [comment]
hey so I just updated the devDependencies and it went fine however there were some issues with the peer dependencies during installation .
Screenshot (8891)
Screenshot (8889)
Screenshot (8890)

**Comment by sarayourfriend** [comment]
I think those errors will be okay, but it could be a configuration issue on our end. I believe we rely on Nuxt pulling in Vue: https://github.com/WordPress/openverse-frontend/blob/a389bb22ea160d2cbd27ec220e08581d24fc5209/pnpm-lock.yaml#L3470

It's pulling in a version that matches the requirements of those peer dependencies, but we probably should declare a specific dependency on Vue rather than relying on it being a transient dependency.

**Comment by kb-0311** [comment]
Thanks . So how should I declare a specific dependency on vue? 

Or should I just submit a pull request of updating these devDependencies for now and that can have its own issue ?

**Comment by sarayourfriend** [comment]
Let's open a separate issue for fixing the peer dependency problems. `pnpm` is complaining that we don't have _explicitly_ declared dependencies on them but otherwise the app should continue to run fine (unless one of the updates introduces a new peer dependency that we haven't addressed). As long as unit and e2e tests continue to pass and a smoke test of the app looks good then we should be okay.

**Comment by zackkrida** [comment]
@kb-0311 I wanted to invite you to the [Making WordPress Slack channel](https://make.wordpress.org/chat/), where you can find folks talking about Openverse in the #openverse channel! If you'd like to participate there, go ahead (you'll need to make a wordpress.org account to join), if not that's okay too.

**Comment by kb-0311** [comment]
Hey @zackkrida thanks, I joined the Slack channel , thanks for the invitation .

**Pull request closed without merging**
