### PR TITLE
Truncate global audio text to two lines

### LINKED ISSUE #758: Audio title in global player component
## Description
On mobile, the global player does not display the audio title correctly. With long audio titles, it shows all characters and blocks the wave area for its interaction. In other cases, it was impossible to close the player.

## Expectation
It should show the audio title in one row with truncated text until reaching the close button area, and be aligned vertically. I would suggest moving upwards the "go to top" button above the player as a transitional solution until we work on a new proposal.

### PR DESCRIPTION
**Pull request by zackkrida**
## Fixes

Related to #758 by @panchovm 

## Description

Truncates the global audio player title to two lines and adds spacing between the title and close buttons.
This doesn't fix the 'back to top' button.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [x] My pull request targets the *default* branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by sarayourfriend — APPROVED** [review]
LGTM! Tested locally and it looks good in RTL and LTR modes (though the global audio player needs some RTL fixes)

**Comment by panchovm** [comment]
The mockup was initially in one row, but it looks good in two rows. Nonetheless, the text alignment is slightly downwards and its width overlaps the close button area. Closing the player does not work properly, but that might be for a new issue.

CleanShot 2022-02-01 at 17 04 17@2x

**Comment by zackkrida** [comment]
@panchovm There's a new issue to fix the close behavior #775, and I actually saw the two lines [used in Figma!](https://www.figma.com/file/w60dl1XPUvSaRncv1Utmnb/Openverse-Releases?node-id=141%3A16511)

**Comment by zackkrida** [comment]
@panchovm I did just fix the text vertical alignment, however! It does look much nicer:

CleanShot 2022-02-01 at 15 29 58@2x

**Review by krysal — APPROVED** [review]
Looks better!

**Pull request merged**
