### PR TITLE
Add missing labels to VPopover

### LINKED ISSUE #1012: Some VPopovers are missing labels
## Description

Some of the Popovers are missing labels and log warnings about it in the console: 
https://github.com/WordPress/openverse-frontend/blob/3ab03476a378768d329e3a21ec0f3a402bb4b560/src/components/VContentReport/VContentReportPopover.vue#L2-L6

https://github.com/WordPress/openverse-frontend/blob/3ab03476a378768d329e3a21ec0f3a402bb4b560/src/components/VFilters/VFilterChecklist.vue#L25

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

### PR DESCRIPTION
**Pull request by obulat**
## Fixes

Fixes #1012 by @obulat

## Description

This PR adds the missing popover labels to ensure that they are accessible.

## Testing Instructions

Run the app and check that the ContentReport popover and the FilterChecklist popover have a11y labels.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [x] My pull request targets the *default* branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by sarayourfriend** [comment]
> Run the app and check that the ContentReport popover and the FilterChecklist popover have a11y labels.

When adding aria attributions we should also test in screen readers so we understand how they're interpreted and how it changes the interaction. I'll be testing in JAWS and NVDA, if someone on a mac could test on VoiceOver that'd be great. IIRC in VO it'll read the aria label of the popover when the popover is focused, I'm not sure how this interacts with something when other text is already focused and we'd want to make sure the label isn't redundant.

**Review by sarayourfriend — APPROVED** [review]
Tested with Chrome on Windows with NVDA and JAWS. NVDA completely ignores the aria label so the popovers still aren't necessarily accessible for NVDA: to fix that we could focus something other than the close button or add more information to the close button label ("Close license explanation", etc). JAWS reads the aria label and stops for the license explanation popover. For the report content one it reads the entire popover contents (I think because the focused element, the close button, isn't labelled).

Opened two issues for this: https://github.com/WordPress/openverse-frontend/issues/1015 and https://github.com/WordPress/openverse-frontend/issues/1016

**Comment by zackkrida** [comment]
Here's a video of VoiceOver in Safari. I _believe_ it is reading the labels before the close button?

https://user-images.githubusercontent.com/6351754/156400799-04061916-7503-4fb0-870d-2a1151ee8090.mp4

**Review by zackkrida — APPROVED** [review]
lgtm. Good incremental improvement!

**Pull request merged**
