### PR TITLE
Regenerate POT files if Vue files have been staged

### LINKED ISSUE #1051: PO file is not regenerated when directories are renamed
## Description

The `pre-commit` action configured by `husky` only generates the PO file when the `en.json` file is changed. But the PO file also changes when directories are named in the code, as that affects the usage of the translations.

This means that there could be events like this:
- Developer changes usage of string from `en.json`.
- Developer lints the code which does not generate the PO file.
- Developer commits this to Git.
- CI check on GitHub flags this as a lint failure.

## Expectation

The PO file generation should be able to identify other cases where it can be changed. At least it should be able to catch the same changes as the CI job does, to prevent commits from reaching GitHub and failing there.

## Additional context

If the PO generation is fast, we could just do it for every commit.

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

### PR DESCRIPTION
**Pull request by dhruvkb**
## Fixes

Fixes #1051 by @dhruvkb

## Description

Since the PO files contain references to Vue components, this PR updates the code that generates them to run when Vue files are in the Git diff.

## Testing Instructions

0. Make some line movements in Vue files. 
0. Move and rename some Vue files.
0. Commit. Your last commit will also contain POT changes.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [x] My pull request targets the *default* branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by dhruvkb** [comment]
In any case, we're not merging PRs till all reasonable checks pass so at the time of merge all differences between the POT and the Vue code will be resolved.

**Review by obulat — APPROVED** [review]
LGTM

**Comment by dhruvkb** [comment]
The issue is that POT generation will include the changed but unstaged files unless those are staged before the commit.

**Comment by sarayourfriend** [comment]
@dhruvkb It did that for the original solution anyway, that's what my comment was about above.

We could move it to pre-push and encourage it to be a separate commit if that would make it clearer. What you said about the PR getting squashed before merge making the commit-level discrepancies irrelevant makes sense to me.

**Comment by dhruvkb** [comment]
This is not a good solution and still leaves room for CI failures.

**Pull request closed without merging**
