### PR TITLE
Unify number localization strategy across the app.

### LINKED ISSUE #535: RTL languages still using eastern arabic numerals on search page
## Description

Some locales will cause eastern arabic numerals to be used for number formatting on the search results page (`ar` for example). In previous discussions with WP i18n folks, we decided to just use western arabic numerals everywhere (like on the sources page). We already have logc in the source page for this:

https://github.com/WordPress/openverse-frontend/blob/92240e443664edb2a9d0c25835d9e1cc1a1f2ee3/src/pages/sources.vue#L175-L184

We should refactor this into a util and then use it everywhere.

## Resolution

- [x] 🙋 I would be interested in resolving this bug.

### PR DESCRIPTION
**Pull request by sarayourfriend**
## Fixes

Fixes #535 by @sarayourfriend

## Description

The issue actually was out-dated, but the solution being used on the search result page differed from the solution used on other parts of the app (namely the sources page).

This PR unifies both approaches and fixes some minor bugs in how the locale was being used for the search results page, and also uses the `en-gb` locale for locales that would have used Eastern arabic numerals.

This also matches the approach taken in Gutenberg for formatting input numbers.

I also managed to get VueI18n into the Nuxt context type so that `useContext`'s return actually includes it, meaning we can add more composables to type checking.

## Testing Instructions

Visit the search page using a locale that uses eastern arabic numerals by default, like `ar` and verify that it is using western arabic numerals instead, like the rest of the locales.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [x] My pull request targets the *default* branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added or updated tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by sarayourfriend** [comment]
@krysal and @obulat would it be possible to get a review on this PR soon? Thanks!

**Review by zackkrida — APPROVED** [review]
This is a very thoughtful addition, love the attention to detail.

**Review by obulat — APPROVED** [review]
I love the unification, thank you for taking care of it!

I have a couple of questions about the locales:
1. How did we choose the locales for the `ARABIC_NUMERAL_LOCALES`?
One concern I have is about the locales that are variants of those locales (ie, for Arabic `ar` locale, there are also Moroccan Arabic `ary` and Algerian Arabic `arq` in our `valid-locales.json` list). I'm not sure how much practical importance that has considering that we don't have those translations.
The other concern is: are there other locales that also need to use a different formatting that we haven't identified?
2. [Nitpicking] Why not use `en` locale instead of `en-gb` for the fallback formatting?

**Comment by sarayourfriend** [comment]
> How did we choose the locales for the ARABIC_NUMERAL_LOCALES?

I'm forgetting the name of the organization and am failing at finding it right now, but there's an org that collects locale metadata from countries all over the world and maps their numeral system (among other things) to the locale.

However, I suppose the _best_ most robust way to do this would be to just format the number and check if it uses anything other than Western Arabic numerals and if it does, then format it using `en`.

I chose `en-gb` becuase the impression I got was that the decimal and thousands delimeter rules followed by `en-gb` more closely matched the expectations from the locales we were intercepting, but I could have gotten that totally wrong. Switching it to just `en` seems fine to me.

**Comment by obulat** [comment]
Thank you for clarifying, @sarayourfriend !

**Pull request merged**
