### PR TITLE
Updated variant name from `plain-dangerous` to `plain--avoid`

### LINKED ISSUE #1181: Change variant name from `plain-dangerous`
## Description
The word dangerous in the `plain-dangerous` variant of `VButton` gives the idea that the button would be used for destructive actions and not that its use is discouraged.

See an example of the confusion here: https://github.com/WordPress/openverse-frontend/pull/1142#discussion_r834307513

## Goal

The intent of developers not using this variant can be conveyed more clearly by using synonyms for "danger" e.g. "beware" and "careful" and my favourite "avoid". I recommend renaming the variant to "plain--avoid". The "--avoid" suffix can add that little bit of friction to discourage it's usage while not confusing with the "danger" convention we use for destructive actions.

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

### PR DESCRIPTION
**Pull request by shreyanshmalvya**
## Fixes

Fixes #1181 by @dhruvkb

## Description

Updated the variant name to plain--avoid in VPlayPause.vue, updated :
```
   /**
     * Sets the button variant to `plain-dangerous` to manually handle focus states.
     * Sets the connections (none-rounded corners) for the button based on the layout.
     */
    const buttonProps = computed(() => {
      const variant = 'plain-dangerous' as ButtonVariant

      return { variant, connections: layoutConnectionsMap[props.layout] }
    })
```
to

```
   /**
     * Sets the button variant to `plain--avoid` to manually handle focus states.
     * Sets the connections (none-rounded corners) for the button based on the layout.
     */
    const buttonProps = computed(() => {
      const variant = 'plain--avoid' as ButtonVariant

      return { variant, connections: layoutConnectionsMap[props.layout] }
    })
```

## Testing Instructions

No errors are given at runtime.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [x] My pull request targets the *default* branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by dhruvkb — COMMENTED** [review]
Please also update the usage in the following places:
Screenshot 2022-08-24 at 6 47 18 PM

**Comment by shreyanshmalvya** [comment]
My Bad, I'll update it right now

**Comment by shreyanshmalvya** [comment]
I have updated the code, @dhruvkb could you review it once?

**Review by sarayourfriend — APPROVED** [review]
LGTM :rocket: Thanks for the PR and the fix :cowboy_hat_face:

**Comment by sarayourfriend** [comment]
Once CI has passed and Dhruv has approved the PR we'll merge it for you :slightly_smiling_face:

**Review by dhruvkb — APPROVED** [review]
All good! Thanks @shreyanshmalvya!

**Pull request merged**
