### PR TITLE
Enable seeking for Jamendo tracks in blink browsers; remove message

### LINKED ISSUE #1681: Remove Jamendo seek notices and enable seeking in blink browsers
## Problem

We now use MP32s from Jamendo and an endpoint which supports the correct headers for streaming audio. We can remove the current logic and related notice which blocks seeking of Jamendo tracks in blink-based browsers.

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

### PR DESCRIPTION
**Pull request by zackkrida**
This PR enables seeking Jamendo tracks as we now use MP32s from Jamendo and an endpoint which supports the correct headers for streaming audio. This PR also removes related strings, the blink browser ua detection hook, and the custom logic to display a notice inside of the audio track for Jamendo in blink browsers.

## Fixes 

Fixes #1681 by @zackkrida 

## Testing Instructions

This needs to be tested against the production api; the dev api is still using old audio files and the seek behavior will not work.

## Checklist

- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [ ] My pull request targets the *default* branch of the repository (`main`) or a parent feature branch.
- [ ] My commit messages follow [best practices][best_practices].
- [ ] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by sarayourfriend** [comment]
The playwright test that is failing is the same one failing for me in #1676.

One of us should add a skip and open an issue.

**Comment by sarayourfriend** [comment]
The changes in this PR work fine for me, except that I still can't seek with Jamendo files. Is there something missing from this? Wouldn't the catalogue need to update the preview url format to make seeking possible? When I look at the network tab Jamendo files are still using `https://storage.jamendo.com/download/track/360978/mp32` format. While it does appear to return `content-length` header now, seeking just sends the audio playback back to 0:00.

**Review by sarayourfriend — APPROVED** [review]
Disregard my comment. This works perfectly as long as you use the production API :slightly_smiling_face:

**Comment by zackkrida** [comment]
@sarayourfriend aaah, sorry for wasting your time. I forgot to include that in the testing notes. We'll also want to update the dev api at some point. Thanks for the review!

**Review by krysal — APPROVED** [review]
Working great 💯

**Review by dhruvkb — APPROVED** [review]
Works as expected for me. I was wondering if we still need the `express-useragent` package if we're only using it to check if the browser is mobile. We can figure that out from the responsive breakpoint media query, right?

**Pull request merged**
