### PR TITLE
Fix double focus ring in item groups

### LINKED ISSUE #766: `focus-visible` polyfill breaking some button focus styles in Firefox
## Description

Buttons are getting double focus rings. I think this is due to the focus-visible polyfill. If it is, then a simple focus could be to only load that polyfill for Safari, it's the only browser that needs it anyway.

Captura de Tela 2022-02-01 às 07 55 34

## Reproduction

1. Run `main` and visit a search page in a small viewport width
2. Open the content type modal
3. Focus the content types with the keyboard
4. Note the double focus outlines

## Expectation

There should be no double focus outlines.

## Environment

 - Device: laptop
 - OS: macOS 11.6.2
 - Browser: Firefox
 - Version: 96.0.3

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

### PR DESCRIPTION
**Pull request by sarayourfriend**
## Fixes

Fixes #766 by @sarayourfriend

## Description

The issue had the wrong diagnosis. It was just a styling error.

## Testing Instructions

Open the content type switcher in the modal and verify that using keyboard to focus does not produce the double focus rings in the issue.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [x] My pull request targets the *default* branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by krysal — COMMENTED** [review]
This removes the outer gray border and the result lookss weird.

CleanShot 2022-02-02 at 09 23 54@2x

**Comment by sarayourfriend** [comment]
Ah! I'm not sure how I missed that. I pushed a fix. It looks like even if you set the `ring-tx` the box-shadow that renders the offset still renders as white? It seems like a bug in Tailwind.

In any case, setting the ring width to `0` removes it completely.

**Review by zackkrida — COMMENTED** [review]
lgtm!

**Review by zackkrida — APPROVED** [review]

**Review by krysal — APPROVED** [review]
Excellent!

**Pull request merged**
