### PR TITLE
Ignore stories from Nuxt build

### PR DESCRIPTION
**Pull request by dhruvkb**
## Description

This PR adds a `.nuxtignore` file to see if that can reduce the Nuxt build size.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [x] My pull request targets the *default* branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by dhruvkb** [comment]
I suppose my hypothesis was wrong. It's something else.

**Comment by sarayourfriend** [comment]
@dhruvkb I think we'd maybe want to exclude the JS stories using the exclude syntax? https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-excluding-paths

**Comment by sarayourfriend** [comment]
But I also have no idea why Nuxt's build appears to be non-idempotent. That is concerning to me.

**Comment by dhruvkb** [comment]
Yeah, random changes seem to be affecting the build size. @zackkrida was right that the output might be noisier than we expected.

**Comment by sarayourfriend** [comment]
Yes, but squashing the output by putting a minimum threshold doesn't solve the problem that nuxt's build isn't idempotent for some reason.

Maybe later today I will try this:

1. Checkout this branch and run a `pnpm build` then copy the `.nuxt` folder somewhere else.
2. Checkout `main` and then run `pnpm build` again
3. Then diff the two folders and see what is different.

**Pull request closed without merging**
