### PR TITLE
Hide the recent searches when navigating with the keyboard

### LINKED ISSUE #1886: Recent searches combobox doesn't close when focus is lost
## Description

If a user tabs through the header navigation, the recent searches popup isn't closed while tabbing through.

## Reproduction

1. Navigate to the search page
1. Press tab until you've navigated into the search bar and the recent searches popup opens
1. Tab out of the search bar
1. Observe the popover is still open

## Screenshots

https://user-images.githubusercontent.com/6351754/194308291-b148d5fe-5dec-48c3-a169-d5cf4f4674b2.mp4

### PR DESCRIPTION
**Pull request by dhruvkb**
## Fixes

Fixes #1886 by @zackkrida 

## Description

This PR hides the recent searches when the keyboard focus moves past the 'Clear' button in the recent searches dropdown.

## Testing Instructions

0. Check out the PR and run the dev server.
1. Repeatedly press <kbd>Tab</kbd>.

## Screenshots

https://user-images.githubusercontent.com/16580576/194470320-272516fb-5d18-4021-9bff-41e9547e0875.mov

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [x] My pull request targets the *default* branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by obulat — COMMENTED** [review]
This solves the happy path problem, and I really love the size of this PR :)

One issue I found is if you navigate to the 'Clear' button, press Enter while on it, and then press Tab again, the recent searches does not close.

We could add a 'Tab' keydown handler to the Search Button and close the Recent searches if they are open.

**Comment by dhruvkb** [comment]
@obulat since the Recent searches dialog come after the Search button in the tab order, if we always hid the recent searches when <kbd>Tab</kbd> is pressed on the Search button, the Clear button would become unreachable. So in f6d01f6 I've set the Search button Tab handler to only hide Recent searches if there are 0 entries.

**Comment by obulat** [comment]
> @obulat since the Recent searches dialog come after the Search button in the tab order, if we always hid the recent searches when Tab is pressed on the Search button, the Clear button would become unreachable. So in [f6d01f6](https://github.com/WordPress/openverse-frontend/commit/f6d01f63bc679382a61f8d4ced1a5365a0af1ffa) I've set the Search button Tab handler to only hide Recent searches if there are 0 entries.

I knew there was a caveat! 😆

**Review by obulat — CHANGES_REQUESTED** [review]
There's one more problem: if you click 'Clear', and then press 'Tab', you don't get to go to the Search button, and you don't trigger the Recent searches Tab handler (why?), so the popup remains open:

https://user-images.githubusercontent.com/15233243/194887206-a95e5552-3dc1-42bf-a594-28d02e5057b8.mov

**Comment by dhruvkb** [comment]
Should we immediately hide the popup when the 'Clear' button is pressed? That would fix this case.

**Comment by obulat** [comment]
> Should we immediately hide the popup when the 'Clear' button is pressed? That would fix this case.

I wonder if hiding it after a short delay is better? This way, the users are not surprised when it is closed immediately, and might even have time to see that the list was emptied and that is why the popup closed?

**Comment by zackkrida** [comment]
Alternatively, should the `clear` button remain visible, but disabled, so it can still hold focus? The timing-based approach sounds good but like it could introduce some confusion or further complexity.

**Comment by obulat** [comment]
What if we focus the input when clicking the 'Clear' button? Then the user can 1. start typing the new value right away or 2. tab away and close the popover.

```
diff --git a/src/components/VHeader/VSearchBar/VSearchBar.vue b/src/components/VHeader/VSearchBar/VSearchBar.vue
index c962ca78f9..b6cf421aa6 100644
--- a/src/components/VHeader/VSearchBar/VSearchBar.vue
+++ b/src/components/VHeader/VSearchBar/VSearchBar.vue
@@ -6,6 +6,7 @@
       @submit.prevent="handleSearch"
     >
       <VInputField
+        ref="inputFieldRef"
         v-bind="$attrs"
         v-model="modelMedium"
         :placeholder="placeholder || $t('hero.search.placeholder')"
@@ -115,6 +116,7 @@ export default defineComponent({
   },
   setup(props, { emit }) {
     const searchBarEl = ref<HTMLElement | null>(null)
+    const inputFieldRef = ref<InstanceType<typeof VInputField> | null>(null)
 
     const { matches: isHomeRoute } = useMatchHomeRoute()
 
@@ -228,9 +230,11 @@ export default defineComponent({
     /* Clear all recent searches from the store. */
     const handleClear = () => {
       searchStore.clearRecentSearches()
+      inputFieldRef.value?.focusInput()
     }
 
     return {
+      inputFieldRef,
       searchBarEl,
 
       handleSearch,
diff --git a/src/components/VInputField/VInputField.vue b/src/components/VInputField/VInputField.vue
index 3137dd64b7..1325cef7f3 100644
--- a/src/components/VInputField/VInputField.vue
+++ b/src/components/VInputField/VInputField.vue
@@ -12,6 +12,7 @@
   >
     <input
       :id="fieldId"
+      ref="inputRef"
       v-bind="$attrs"
       :type="type"
       class="h-full w-full appearance-none rounded-none bg-tx text-2xl font-semibold leading-none placeholder-dark-charcoal-70 ms-4 focus:outline-none md:text-base"
@@ -27,9 +28,15 @@
 </template>
 
 <script lang="ts">
-import { computed, defineComponent, PropType } from '@nuxtjs/composition-api'
+import {
+  computed,
+  defineComponent,
+  PropType,
+  ref,
+} from '@nuxtjs/composition-api'
 
 import { defineEvent } from '~/types/emits'
+import { ensureFocus } from '~/utils/reakit-utils/focus'
 
 export const FIELD_SIZES = {
   small: 'h-10 text-md',
@@ -99,6 +106,8 @@ export default defineComponent({
     'update:modelValue': defineEvent<[string]>(),
   },
   setup(props, { emit, attrs }) {
+    const inputRef = ref<HTMLInputElement | null>(null)
+
     const type = typeof attrs['type'] === 'string' ? attrs['type'] : 'text'
 
     const updateModelValue = (event: Event) => {
@@ -106,12 +115,20 @@ export default defineComponent({
     }
     const sizeClass = computed(() => FIELD_SIZES[props.size])
 
+    const focusInput = () => {
+      if (inputRef.value) {
+        ensureFocus(inputRef.value)
+      }
+    }
+
     return {
+      inputRef,
       emit,
       type,
 
       sizeClass,
       updateModelValue,
+      focusInput,
     }
   },
 })

```

**Comment by dhruvkb** [comment]
@obulat I tried your suggestion (almost verbatim, I realise now) and it works pretty well. The UX is pretty good and functionality-wise it does what one would expect. Thanks!

**Review by obulat — APPROVED** [review]
Works well! 👍 
It needs rebasing / merge now that ClientOnly is merged.

**Review by zackkrida — APPROVED** [review]
LGTM but we also need to handle the case when tabbing _backwards_ (to the Openverse logo), which currently keeps the popup open. A separate PR and issue is fine there.

**Pull request merged**
