### PR TITLE
Incorrect text styles in metadata information

### LINKED ISSUE #1587: Incorrect text styles in metadata information
## Description
In the single result view of audio content, the metadata information shown in the Audio information section has incorrect styles. The font size is `16px` and line-height `32px`, while it should follow the [metadata item component](https://www.figma.com/file/GIIQ4sDbaToCfFQyKMvzr8/Openverse-Design-Library?node-id=1043%3A3305) definitions.

## Reproduction
1. Search for anything and see audio results.
2. Click on any audio track to see its details.
3. See the Audio information section.

## Resolution
- [ ] 🙋 I would be interested in resolving this bug.

### PR DESCRIPTION
**Pull request by ramadanomar**
## Fixes

Fixes #1587 by @panchovm
Check PR #1611 for more info
## Description

Adds the correct meta-element styles.
image

image

## Testing Instructions

Select Audio, Search any title and check the meta elements
## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [x] My pull request targets the *default* branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added or updated tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by obulat — APPROVED** [review]
This is great! Thank you for the clean PR :)

**Comment by panchovm** [comment]
I am seeing the following styles

* **Tag pill label:** Font size `14px` and line-height `18px`.
* **Metadata category:** Font size `16px` and line-height `32px`.
* **Metadata value:** Font size `14px` and line-height `21px`.

**Tag pill label** and **metadata value** should follow `description bold` style, whereas **Metadata category** should follow `description regular` style. Both text styles are font-size `14px` and line-height `18px`, but the font-weight changes.

You can see all text styles in the [Design Library's page](https://www.figma.com/file/GIIQ4sDbaToCfFQyKMvzr8/Openverse-Design-Library?node-id=309%3A214).

**Comment by ramadanomar** [comment]
> **Tag pill label** and **metadata value** should follow `description bold` style, whereas **Metadata category** should follow `description regular` style. Both text styles are font-size `14px` and line-height `18px`, but the font-weight changes.

The closest line-height i can find in the [tailwind utility page](https://wordpress.github.io/openverse-frontend/_preview/1593/tailwind/#Line%20Height) is 1rem 16px (leading 4). 

Should we update tailwind classes to match line-heights from the FIGMA document?

**Review by panchovm — CHANGES_REQUESTED** [review]
The text styles look great, but I just noticed that metadata in the image details view has a top margin of `8px (0.50rem)`. Here is what I see in the image version of the same page.

CleanShot 2022-08-19 at 14 40 22@2x

**Comment by ramadanomar** [comment]
done
I also capitalized each word in the Genre category to match the Audio Release Figma Files

**Comment by panchovm** [comment]
I just noticed [my previous comment](https://github.com/WordPress/openverse-frontend/pull/1645#pullrequestreview-1079236054) was completely miswritten.

I wanted to say that between both labels, category and value, there should be a `8px` spacing, like [this mockup](https://www.figma.com/file/w60dl1XPUvSaRncv1Utmnb/Audio-Release?node-id=978%3A23773). On the other hand, the capital feature looks excellent; great idea.

Sorry for the mistake 🤦‍♂️

**Comment by ramadanomar** [comment]
> Sorry for the mistake man_facepalming

My bad, i was only checking the individual text styles in css without looking at the whole object's properties. Should be fixed.

**Comment by zackkrida** [comment]
@panchovm what should the line-height be when the album title is multiple lines long? I think currently it might be too large, here's an example:

https://search.openverse.engineering/audio/7e063ee6-343f-48e4-a4a5-f436393730f6

Might want to fix that in this PR too.

**Comment by ramadanomar** [comment]
> Might want to fix that in this PR too.

image
Even for larger titles, the title doesn't wrap. Mind detaling on what multiple lines means

**Comment by zackkrida** [comment]
Apologies @ramadanomar, referring to the album title in _this section_, the "I love my dog..." pink text next to the album art:
CleanShot 2022-08-23 at 12 13 50@2x

Example: https://search.openverse.engineering/audio/7e063ee6-343f-48e4-a4a5-f436393730f6

**Comment by ramadanomar** [comment]
Oh, you’re right. It looks kind of weird.

**Comment by panchovm** [comment]
Both Description regular and Description bold styles have the same line height.

CleanShot 2022-08-23 at 14 08 11@2x

And here is how looks @zackkrida's example in a Figma mockup.

CleanShot 2022-08-23 at 14 10 23@2x

**Comment by zackkrida** [comment]
Great, so we should fix that line height in this PR as well. Thank you @panchovm !

**Comment by ramadanomar** [comment]
image
Turns out it is fixed with this PR

**Review by zackkrida — APPROVED** [review]
LGTM! This looks ready.

**Review by panchovm — APPROVED** [review]
It looks great ✨

**Pull request merged**
