### PR TITLE
Update Audio and Image's action button text

### LINKED ISSUE #1341: Discrepancy between action buttons on single result page
## Description

The "action" button on a media's single result page is different between images and audio. For images, it says `Go to image's website`, but for audio it says `Download`. For users looking to download media, this discrepancy can create confusion.

## Reproduction

* Image example: https://search-staging.openverse.engineering/image/0439408c-11ae-490e-a10a-8139766f68fb
* Audio example: https://search-staging.openverse.engineering/audio/5a679d59-5868-4339-b208-50a05770a2a2

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

### PR DESCRIPTION
**Pull request by krysal**
## Fixes

Fixes #1341 by @AetherUnbound 

## Description

Replace the "Download" with "Go to audio's website", a text in line with the Image Details page. We step back in offering downloading audio directly from Openverse.

## Testing Instructions

Run the project and visit any audio details page to see the updated button.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [x] My pull request targets the *default* branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added or updated tests for the changes I made (if applicable).
- [N/A] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by obulat — APPROVED** [review]
LGTM!

**Comment by panchovm** [comment]
Thanks for working on this consistency.

I posted a design issue (#1701) proposing tweaking this and the homepage. Worth taking a look and maybe addressing the discussion about copy in that ticket.

Regarding this PR, the change looks great on desktop, but on mobile, the button style looks the same. It should change as the [component definition](https://www.figma.com/file/GIIQ4sDbaToCfFQyKMvzr8/Openverse-Design-Library?node-id=558%3A2288). Here is what I see of both buttons on a `375px` viewport.

CleanShot 2022-08-19 at 14 49 14@2x

**Comment by krysal** [comment]
@panchovm I updated the styles for the button. This is how it looks for audio:

### Mobile

localhost_8443_audio_cb524dd5-029d-4698-b83a-88e83b64e5bb(iPhone SE)

--- 

### Desktop

CleanShot 2022-08-22 at 12 44 53@2x

Waiting for your comments to confirm these are the correct styles.

**Review by panchovm — APPROVED** [review]
It looks perfect. Great job ✨

**Pull request merged**
