### PR TITLE
Support for video page and additional content types

### LINKED ISSUE #631: Content switcher with Audio as beta and Video as Meta search
## Problem
As discussed on the public channel, the audio releases will be in Beta as we are still improving the integration. In parallel, openverse displays a list of additional sources for video content under an open license. None of the current mockups include these two situations.

## Description
Here is a new version of the content switcher showing both actions: Audio in Beta, and Video as Additional type. Here is a screen recording showing the interaction.

### Desktop
https://user-images.githubusercontent.com/895819/149994168-cb7bb81e-aec1-400c-bc8b-2037312bdef7.mp4

### Mobile
https://user-images.githubusercontent.com/895819/149994715-a9822e9e-555d-4345-89f9-b584574cc464.mp4

Note: The video above misses a step. After selecting the video option, the menu closes and video results page is visible. The video item selected is only visible once opening the menu on video results page.

## Additional context
The Beta pill is a new component requested on issue #630

### PR DESCRIPTION
**Pull request by obulat**
## Fixes

Fixes #631 by @panchovm 

## Description

This PR adds support for the video page with Additional sources form. It also refactors the way search types are handled to enable using a non-supported search type, too.

I am setting this as medium priority, but it may be 'high' because the `model_3d` work depends on these changes.

I have a question about what to do when a user tries to search from a non-supported type search page (i.e., video). When the user enters a search term on the Video page and clicks 'Search', we can:
1. automatically search for All Content - redirect to the All Content page
2. update the path and set the search term in the store, but do nothing else. This way, the user can change the search type using the content switcher, and be redirected to the same query for other search types? Here, we can also use some 'popup'/ 'toast' indication saying that search for video is not available.
3. do nothing (maybe with some kind of indication like a toast saying that search is not available for 'video')

I think I would expect the second option if I was the user. What do you think, @panchovm ?

## Testing Instructions

Open the video page (http://localhost:8443/search/video or http://localhost:8443/search/video/?q=cat). It should not be broken, and should show the Additional sources buttons that redirect to video search on the provider sites.
Changing the search type in the content switcher should also work.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [x] My pull request targets the *default* branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by zackkrida** [comment]
This looks great! I think #2 would be best, so that the 'additional source' urls update when a new search is submitted. 

@panchovm we can discuss this in a separate PR, but I experimented with reducing the vertical padding of the content switcher. I'm just concerned about the height of this element as we add more types. Here are some examples of reduced padding:

CleanShot 2022-04-16 at 11 19 18@2x
CleanShot 2022-04-16 at 11 18 39@2x

**Comment by zackkrida** [comment]
Oh @obulat one more thing, should/could we add the Models 3D page in this PR as well? Seems like a fairly easy addition given the work you've put in!

**Comment by obulat** [comment]
Do we want to use `/model_3d/` as a slug? If so, then the file name for the page (`model_3d.vue`) becomes not "kebab-cased", so we'll need to overrule the ESLint rule for this file.

**Comment by zackkrida** [comment]
That's a good question regarding what the best slug is. A hyphen would be much more conventional–maybe we should jut change to `model-3d` everywhere

**Comment by panchovm** [comment]
I like solution 2 too. I think it is the most expected behavior.

Noting that this implementation is related to ticket #1124 and the mockups are available in [this Figma file](https://www.figma.com/file/IFIqt7Q3MEKMLSnBedzHBO/Next-Release-%5BTBD%5D?node-id=2%3A48).

Regarding @zackkrida's exploration, I like the outcome. I would reduce the sides' paddings to have the same white space effect on all sides. Did you check [the component's last version](https://www.figma.com/file/GIIQ4sDbaToCfFQyKMvzr8/Openverse-Design-Library?node-id=558%3A2283)? It looks very similar, and I think there is a current issue requesting the spacing update.

**Comment by zackkrida** [comment]
@obulat have you seen @panchovm's design for these pages, in this PR? https://github.com/WordPress/openverse-frontend/issues/1124

It includes disabling the filter bar on these pages.

**Comment by sarayourfriend** [comment]
We never got to discuss the language around them.

I'll reshare my thoughts about the names here:

* "Additional" implies that they are in Openverse somehow, like "audio" in addition to "image" search. It doesn't follow from "additional" that the searches are _external_, which to me is a clearer term, "External search engines" or even more simply "Other search engines".
* The word "source" probably doesn't mean much to a new Openverse user. Even provider could be vague, as we don't educate users clearly about where the results are coming from until they get to the single result page and start seeing that such and such result is from Flickr or Freesound or wherever. Design earlier in the search funnel could help this (and we know that some of our providers feel too hidden by our current approach)? It's hard to know if this is actually a problem though, given we can't user test :cry:  I'm just guessing based on what I think the average new user will know about Openverse ("a search engine for openly licensed media", I wonder if the average non-technical person thinks of "search engine" as an aggregator like technical folks probably understand it to mean).

**Comment by panchovm** [comment]
I like the word External. It is more explicit about the browser experience where Openverse showcase other search engines.

Regarding sources, I agree that is difficult to understand. It is not just the term but also the experience we are providing. This needs an improvement on the single result view to stand out the source/provider name, and probably some Homepage tweak showing the variety of sources living in the search results.

Fortunately, we have discussed the latter, so I would keep the discussion once I can work on a proposal for this scenario.

**Comment by zackkrida** [comment]
I like the simplicity of 'Other search engines'; the fact that we describe openverse as a 'search engine' should mean they're familiar with the term. I'm also comfortable with 'other sources', since we have a 'source' filter and a 'sources' page.

**Comment by obulat** [comment]
So, looking at https://github.com/WordPress/openverse-frontend/issues/1124, the new copy for the video and 3d model pages will be:

> _Video_ search is still under development. Try one of the _<???>_ below.

I like the "other search engines" for the <???> part:

> _Video_ search is still under development. Try one of the _other search engines_ below.

**Comment by obulat** [comment]
I am going to close this PR because the implementation of Video pages after the introduction of Feature flags changes a bit. #1430 makes it so that going to the `/search/video` URL doesn't crash the app, and #1410 puts the additional search types behind a feature flag.

**Comment by obulat** [comment]
I am going to close this PR because the implementation of Video pages after the introduction of Feature flags changes a bit. #1430 makes it so that going to the `/search/video` URL doesn't crash the app, and #1410 puts the additional search types behind a feature flag.

**Pull request closed without merging**
