### PR TITLE
Check paginated versions during Rollback version check

### LINKED ISSUE #1623: Rollback script only looks at most recent 10 versions of the frontend image
## Description

If you try to rollback to a valid version that is not on the first page of results the rollback workflow will fail: https://github.com/WordPress/openverse-frontend/actions/runs/2803805784

## Reproduction

1.  Dispatch the rollback workflow to a valid version that is not on the first page of results from the package version endpoint
2.  See the failure from the link in the description.

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

### PR DESCRIPTION
**Pull request by sarayourfriend**
## Fixes

Fixes #1623 by @sarayourfriend 

## Description

Paginates through the image versions instead of relying just on the first page of 30 results.

## Testing Instructions

Merge and try to re-deploy production to v3.4.2 (which is not previously on the first page).

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [x] My pull request targets the *default* branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [N/A] I added or updated tests for the changes I made (if applicable).
- [N/A] I added or updated documentation (if applicable).
- [N/A] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by zackkrida** [comment]
I believe the loop runs infinitely in the case where the tag doesn't exist and it runs out of pages. 

BTW I was able to test this locally with Octokit. Just need a personal access token with `read:package` permissions.

```js
const { Octokit } = require("@octokit/rest");

const github = new Octokit({
  auth: "your_key_here",
});

async function go() {
  let exists = undefined,
    versions = [],
    page = 0;

  do {
    page += 1;
    ({ data: versions } = await github.rest.packages.getAllPackageVersionsForPackageOwnedByOrg({
      package_type: "container",
      package_name: "openverse-frontend",
      org: "WordPress",
      page,
      // max of `per_page`
      per_page: 100,
    }));

    exists = versions.some((v) => v.metadata.container.tags.includes("v3.4.2"));
  } while (!exists || versions.length === 0);

  if (!exists) {
    throw new Error(
      "`${{ inputs.tag }}` does not appear to be a valid tag for the ghcr.io/wordpress/openverse-frontend image."
    );
  }
}

go().then(() => console.log("done!"));

```

**Comment by sarayourfriend** [comment]
Ah, thanks for the tip! I will try it locally. I think the while condition needs to be an `&&` :slightly_smiling_face:

**Comment by sarayourfriend** [comment]
It ended up being clearer to just use an explicit break instead of overloading the condition.

**Review by AetherUnbound — APPROVED** [review]
Looks good!

**Pull request merged**
