### PR TITLE
Add title bottom spacing

### PR DESCRIPTION
**Pull request by 0kyn**
This PR fixes spacing missing between the title and body content.

## Screenshots

Add title spacing on `search-help` view
search-help

Title spacing seems to be already present on `feedback` view
feedback-title

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [x] My pull request targets the *default* branch of the repository (`main` or `master`).
- [x] My commit messages follow [best practices][best_practices].
- [ ] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no visible errors.

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by zackkrida — APPROVED** [review]
This looks perfect, thank you @0kyn and welcome to open source 😆

**Comment by dhruvkb** [comment]
Hey @0kyn! Good work on the PR. 

I should point out though that issues where someone has recently expressed intent to work should not be considered for raising a PR. This can lead to a lot of wasted effort for the person who might have already started working for a fix.

**Comment by 0kyn** [comment]
My bad... I'm truly sorry @theshakeabhi, and thank you @dhruvkb for the advice. I need some good habits and practices!

Should I asked into the issue if another dev still working on it?

**Comment by dhruvkb** [comment]
It's not a problem at all, 0kyn. We are always learning better ways to collaborate.

But yeah, asking is a good way to make sure that someone is not already working on it. Or maybe if there hasn't been any activity for a few days, you can assume that it's available.

**Comment by theshakeabhi** [comment]
hey @0kyn, it's absolutly not a problem. As @dhruvkb mentioned we are all learning to collaborate. Cheers on your PR getting merged.

**Pull request merged**
