### PR TITLE
 Correct heading order for single audio result pages

### LINKED ISSUE #1616: Correct heading order for single audio result page
## Problem

The heading order of single result pages (for example, https://search.openverse.engineering/audio/2ecd5631-c48c-4a5f-89c4-83c44dbbd365) is currently incorrect. `h2` and `h4` headings are skipped.

This issue was originally for both audio and image results, but then issue  #1698 was opened to track the image detail page.

## Description
The heading order should be logical (h1 - h6) and not skip levels. The styles should still match the design mockups.

### PR DESCRIPTION
**Pull request by kickeyhickey**
## Fixes
Fixes #1616 by @obulat 

## Description
- Pull Request changes the headers of the following components to be a in sequential order ( h1 - h3)
        (h1) * src/components/VMediaInfo/VMediaReuse.vue
        (h2) * src/components/VAudioDetails/VAudioDetails.vue
        (h3)  * src/components/VAudioDetails/VRelatedAudio.vue
- Pull Request changes testing file 'related-audios.spec.js' to pass 'RelatedAudios' test. 'h4' has been changed to 'h3'. Test now passes. 

##Add screenshot
openverse issue#1616

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [x] My pull request targets the *default* branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by kickeyhickey** [comment]
Hello @obulat 
I hope we understood the changes that needed to be made on this one. I also fixed a test that failed due to my edits. Please let me know if I'm on the right track and if any edits are needed we'll fix them right up for you. 
cc: @RARNE12  @Jbudd512

**Comment by obulat** [comment]
Thank you for working on this issue, @kickeyhickey, it's a pretty good start! Great that you could fix the tests, too 🎉

The heading levels will need to be adjusted because there is already an `<h1>` heading on the page that is the audio title. Here is the image showing which heading levels should be used:

Audio

Also, I just realized that I only described the audio detail page in the issue, but the image detail page needs the same adjustments. Would you like to tackle the image detail page in this PR, too? Or would you prefer for me to edit the parent issue to add the image detail page as a separate issue?

**Review by obulat — CHANGES_REQUESTED** [review]
The Playwright tests will also need to be adjusted after you finish the other changes. I can help with them later if you need :)

**Comment by kickeyhickey** [comment]
@obulat I went ahead and made the necessary changes via your provided picture. Appreciate your help. I also changed the Rspec test to reflect our changes. I hope this does it.
@RARNE12 will put a PR together for the image page. We'll get to work on that for you and will mention this ticket.

CC: @Jbudd512

**Comment by RARNE12** [comment]
@obulat , Hello, just connected my PR  #1678 to this PR. We updated the PR, but we did come across some playwright issues. Any assistance you can provide in fixing this issue would be appreciated.

cc: @Jbudd512
cc: @kickeyhickey

**Review by obulat — APPROVED** [review]
I've rebased onto main and added a couple of small changes to `media-reuse.spec.ts` and `related-audios.spec.js` to make the tests pass.

The changes work great, and now the heading order is accessible! Thank you for your contribution, @kickeyhickey, and welcome to Openverse 🎉

**Review by zackkrida — APPROVED** [review]
Excellent; lgtm.

**Pull request merged**
