### PR TITLE
Only download data for locales with more than 70% translations

### PR DESCRIPTION
**Pull request by obulat**
## Description

This PR queries the main Openverse translations page for locales for which more than 70% has been translated, and only downloads data for those locales. The 70% is arbitrary, and I'm open to suggestions here.

This is done to reduce the number of downloads and files that we save to the repository.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [ ] My pull request targets the *default* branch of the repository (`main` or `master`).
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by zackkrida** [comment]
This is a very cool approach, thank you! I'm wondering about the `70%`, I think my current feeling is the following:

1. Only show languages with 100% translation

OR

2. Show all languages with _any_ percentage of translation, with a banner saying "This translation is incomplete, please contribute at {glotpress url}

I'm not sure what the best experience for users is though, we can discuss this at the team meeting tomorrow.

**Comment by zackkrida** [comment]
> This is done to reduce the number of downloads and files that we save to the repository.

Also, in #151 I'm **not** currently saving the translation files in the repository, they're actually in the `.gitignore`.

**Comment by sarayourfriend** [comment]
What's the reason to reduce the number of files saved anyway?

From my perspective, the solution that promotes the most community involvement is the second option Zack listed.

**Comment by obulat** [comment]
As a website user, I don't like when languages are mixed on a website.

I suspect that having all languages with a banner asking for help translating would increase a tiny community involvement percentage, at the expense of annoyance to a great majority of users who will not get involved. It might be breaking the trust of a user who are promised the site in their language, but get a mix of languages instead.

Am I over applying my own feelings? It would be great to get opinions of users and others who work on i18n.

**Comment by sarayourfriend** [comment]
That's a good point Olga. I find it frustrating when apps and websites are only half translated to Portuguese as well.

I wonder how the WordPress Learn project decided to do the second option?

**Comment by dhruvkb** [comment]
+1 for the 'incomplete translations' banner. Anything less than a 100% should lead to the banner being shown imo.

**Comment by zackkrida** [comment]
I'm going to close this for now, with the potential of re-opening it in the future. Thanks Olga!

**Pull request closed without merging**
