### PR TITLE
Style links globally

### PR DESCRIPTION
**Pull request by krysal**
## Description

This small change will save us from copying the styles for links several times in every place where one appears (I was doing this in the single result page for images). The default color is pink and they should have an underline on hover state.

## Testing Instructions

Run the project, everything should look the same. Writing a new link should have the default styles without requiring to do anything else.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [x] My pull request targets the *default* branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by zackkrida — APPROVED** [review]
I love this idea! I'm wondering if there's a 'safer' way to implement it. For example, one idea would be a `<TextLink>` component that wraps a `<NuxtLink>` and applies the default text link styles. 

Despite that, I think your approach works well because it ensures plain links are accessible against our standard text color by default 👍

**Review by obulat — APPROVED** [review]
I like how much cleaner the class lists look now!
This approach might be a good way to get rid of the scss styles in the future, too.

**Review by dhruvkb — COMMENTED** [review]
Instead of styling `a` directly on the base, could we create a new Tailwind component like so
```css
@layer components {
  .text-link {
    @apply text-pink hover:underline;
  }
}
```

so that it only applies when we explicitly call for it to be applied?

In my experience, it's easier to apply classes when needed rather than unapply them when they're applied by default.

But yeah, I do appreciate that links are no-longer colored the same as regular text.

**Comment by krysal** [comment]
I precisely wanted to forget about repeating classes for normal links 😆 I pondered whether to create a new component or not but seemed not worth it for me. This is just a change in styles that certainly should be global. One can forget to use the customized link component, go directly with an `a` element and forgot to apply the styles. 

Although it can be a good idea if we add the function to vary between an internal and external link if Openverse continues to exist in an iframe. If this change turns out to be more problematic in the future I'll happily create the component.

**Pull request merged**
