### PR TITLE
Fix icon of dropdown button

### LINKED ISSUE #1180: Odd audio download behavior (missing dropdown icon, repeated format)
## Description

The download button for audio is showing no icon and a repeated `mp3` format on this particular page:

https://wordpress.org/openverse/audio/9af3243a-e4d4-4254-95d9-a3d53a0158c3/

CleanShot 2022-03-24 at 09 03 49@2x

### PR DESCRIPTION
**Pull request by krysal**
## Fixes

Fixes #1180 by @zackkrida 

## Description

This PR:
- Standardize the caret icon with the `g` container element
- Adds the icon to the dropdown button
- Renames components with the `V` prefix

## Testing Instructions

Visit the following link and observe that the button has the caret icon:
http://localhost:8443/audio/9af3243a-e4d4-4254-95d9-a3d53a0158c3

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [x] My pull request targets the *default* branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added or updated tests for the changes I made (if applicable).
- [N/A] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by obulat — COMMENTED** [review]
I think we still do need to add format filter on the front end as well for correctly handling duplicate alt_files. Something like this in the fullLayout getFormats can work
```
const getFormats = (audio) => {
      if (audio.alt_files?.length) {
        let extensions = new Set()
        const filteredAltFiles = audio.alt_files.filter((altFile) => {
          const isUnique =
            altFile.filetype !== audio.filetype &&
            !extensions.has(altFile.filetype)
          extensions.add(altFile.filetype)
          return isUnique
        })
        if (filteredAltFiles.length) {
          return filteredAltFiles.map((altFile) => ({
            extension_name: displayFormat(audio.provider, altFile.filetype),
            download_url: altFile.url,
          }))
        }
      }

      return [
        {
          extension_name: displayFormat(audio.provider, audio.filetype),
          download_url: audio.url,
        },
      ]
    }
```

**Comment by sarayourfriend** [comment]
@obulat For the duplicate formats are they the various mp3 bitrates that some providers have? In that sense they're not "duplicates", we're just missing information that should be encoded in them.

I _thought_ we'd discussed mapping this by hand on the frontend somewhere but I can't remember when that conversation happened or if an issue ever was created for it.

**Comment by zackkrida** [comment]
> I thought we'd discussed mapping this by hand on the frontend somewhere but I can't remember when that conversation happened or if an issue ever was created for it.

FWIW I recall this too.

**Review by sarayourfriend — APPROVED** [review]
LGTM, fixed the dropdown icon issue which is the only part in scope for this.

Let's open a separate issue/continue the discussion about how to handle download file types elsewhere.

**Review by zackkrida — APPROVED** [review]
lgtm!

**Comment by krysal** [comment]
I thought about the different bit rates too and it seems that those are duplicated in the catalog/from the API: https://api.openverse.engineering/v1/audio/9af3243a-e4d4-4254-95d9-a3d53a0158c3/

<details>
<summary>Response</summary>

```
{ ...
"alt_files": [
        {
            "url": "https://freesound.org/apiv2/sounds/20015/download/",
            "bit_rate": "192000",
            "filesize": "2397312",
            "filetype": "mp3",
            "sample_rate": "44100"
        },
        {
            "url": "https://freesound.org/apiv2/sounds/20015/download/",
            "bit_rate": "192000",
            "filesize": "2397312",
            "filetype": "mp3",
            "sample_rate": "44100"
        }
    ],
}
```

So hiding it here is not the final solution although we could do it while solving the ingestion step, but I prefer to tackle that in the catalog first.
</details>

**Pull request merged**
