### PR TITLE
Put back focus-ring above md sizes

### LINKED ISSUE #875: Pages menu lacks focus styles
## Description

The three-dot/pages menu on Openverse lacks focus styles on the interior buttons. 

We should possibly do one or both of the following:

1. We should apply the existing hover styles to focus as well by duplicating them and replacing the `hover:` class prefix with `focus:`.
2. We should apply the standard pink focus outline to the active item

@panchovm @sarayourfriend from an a11y perspective, which approach should we take?

## Reproduction

1. Visit https://wordpress.org/openverse/search/?q=dogs
2. Tab over to the menu
  CleanShot 2022-02-15 at 12 13 10@2x
3. Observe that when focusing on items and navigating via keyboard, there is no visual indication.

### PR DESCRIPTION
**Pull request by sarayourfriend**
## Fixes

Fixes #875 by @zackkrida 

## Description

Adds back the focus ring above `md` size. @obulat do you remember why this was disabled? I tested the other places that use the item group and I couldn't find anywhere that this caused a problem but might have missed something.

## Testing Instructions

Follow repro steps in the linked issue and confirm the focus-ring is visible now.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [x] My pull request targets the *default* branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [N/A] I added or updated tests for the changes I made (if applicable).
- [N/A] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by obulat** [comment]
@sarayourfriend , if I remember correctly, I removed it because content type items have a focus ring inside the box borders/ outside the box borders based on the screen size. You can see the components in the [figma mockups](https://www.figma.com/file/GIIQ4sDbaToCfFQyKMvzr8/Openverse-Design-Library?node-id=405%3A2017).

**Comment by sarayourfriend** [comment]
@obulat I guess when I don't really understand is that in staging there isn't a focus ring at all on the search type popovers. And the search type switcher doesn't appear anywhere on the page as a popover below `md` screen widths anyway, does it?

**Comment by obulat** [comment]
Yes, it is all wrong now, I'm not sure what broke it

**Review by obulat — APPROVED** [review]
Very important fix!

**Comment by obulat** [comment]
I am closing this because this change was the base for #897, and that PR is already merged.

**Pull request closed without merging**
