### PR TITLE
Add interaction styles to the content switcher

### PR DESCRIPTION
**Pull request by obulat**
## Fixes

N/A

## Description

This PR adds hover and focus styles to the content switcher items in the popover/modal.
To show a pink outline _inside_ the `VItem`, I had to change the `grouped` button to have an outline inside its `content` instead of the button itself. It might break some other buttons that used `grouped` variant, but I haven't found any.

## Testing Instructions

Run the app and test the content switcher interactions.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [ ] My pull request targets the *default* branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by sarayourfriend — APPROVED** [review]
LGTM! The `grouped` variant is meant for the `VItemGroup` anyway and I don't believe it's used anywhere as you said. 👍 Change makes sense to me too.

I did notice one thing as I was testing this was that on the mobile version, using the keyboard to open the content switcher results in the logo being focused instead of the content switcher. Do you want me to open an issue for that @obulat?

**Comment by obulat** [comment]
> I did notice one thing as I was testing this was that on the mobile version, using the keyboard to open the content switcher results in the logo being focused instead of the content switcher. Do you want me to open an issue for that @obulat?
Yes, opening an issue would be nice, @sarayourfriend !
I really can't figure out the focus trap here...

**Comment by sarayourfriend** [comment]
Oh, the other thing that I guess this PR introduces is that the `beta` pill is right aligned to the focus ring now:

Captura de Tela 2022-01-19 às 11 47 41

Given this PR isn't against `main` feel free to fix that here or in the other PR.

**Review by zackkrida — APPROVED** [review]
LGTM! Lets fix the placement issue in the other PR

**Pull request merged**
