### PR TITLE
Make `isNewHeaderEnabled` a computed so that it's updated

### LINKED ISSUE #1891: Layout not updated because the `new_header` flag status is set once
## Description

The layout is not updated when you check the `new_header` checkbox.

## Reproduction

1. Run the app.
2. Go to `/preferences` page and check the `new_header` checkbox.
3. See error: the header should be updated to the VHeaderInternal, but instead it stays the same. The layout stays the same (without the new header) until you reload the page.

## Additional context

The `isNewHeaderEnabled` variable in the `default.vue` layout should be a computed so that it is updated when the feature flag value changes.

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

### PR DESCRIPTION
**Pull request by obulat**
## Fixes

Fixes #1891 by @obulat

## Description

This PR makes  `isNewHeaderEnabled` a computed so that it's updated when you check the `new_header` checkbox on the Preferences page.

## Testing Instructions

Go to the Preferences page (http://localhost:8443/preferences) and check the `new_header` flag. You should see the header updated immediately (it should now have internal links).
You can also try the [staging](https://search-staging.openverse.engineering/preferences) to see that the header there is not updated until you reload the page.

## Checklist

- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [ ] My pull request targets the *default* branch of the repository (`main`) or a parent feature branch.
- [ ] My commit messages follow [best practices][best_practices].
- [ ] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by dhruvkb — CHANGES_REQUESTED** [review]
You'll need to add `.value` to its usages in the `<script>` section. I can't review those parts as they haven't changed.

**Comment by zackkrida** [comment]
@dhruvkb and @obulat do you think it would be more robust long-term to make the `isOn` method of the feature flag store return a computed value?

**Review by dhruvkb — APPROVED** [review]
@obulat LGTM!

@zackkrida it could make sense to make the `isOn` be a computed property, but wouldn't components using it still need to put the value inside a `computed` call?

**Comment by dhruvkb** [comment]
I just realised that this might break the "feature" that flags toggled using `ff_` query params remain the same for the entire session.

**Comment by obulat** [comment]
> I just realised that this might break the "feature" that flags toggled using `ff_` query params remain the same for the entire session.

Which change might break the query param feature, @dhruvkb ? The one in this PR, or Zack's suggestion about returning a computed from isOn?

**Comment by dhruvkb** [comment]
The one in this PR.

**Comment by obulat** [comment]
> I just realised that this might break the "feature" that flags toggled using ff_ query params remain the same for the entire session.

What should the behavior be when you open the preferences and uncheck the checkbox that was previously set using a query param? 🤔
I can see two options here:
- if a flag is set using a query param, it is set to a special state so that it becomes not switchable using the query param. The feature's Preferences page checkbox is set to 'disabled'.
- the query param is NOT guaranteed to be used if the user uses the UI in the Preferences page to change it. So, you can go to the `/preferences?ff_new_header=off` and check the 'new_header' feature to set the flag to be `On`.

My personal preference would be the second option, but maybe it's because I can only see this used in the current situation, and not for the future feature flag. We wanted the query parameter for a flag feature to be able to show the feature to the stakeholders (e.g. on staging) without having them set up the app locally. It should be possible to revert the flag state using the UI in such a case.

I wonder if we should add the feature flags to the routing: if the flag is set, the query is always shown in the URL. This way, it will always be synced with the cookie state, and you would be able to update the flag value both on the preferences page, and by changing the query param.

**Review by zackkrida — APPROVED** [review]
👍

**Pull request merged**
