### PR TITLE
Reduce GlotPress limit further to ensure all languages

### LINKED ISSUE #2170: Not all locales show up in picker
## Description

It appears that not all translated locales are showing up in the locale picker on openverse.org. For instance, Romanian appears fully translated (https://translate.wordpress.org/projects/meta/openverse/) but does not appear in the dropdown.

@krysal pointed out that the Romanian locale file is present locally but it also doesn't show up in staging either.

## Reproduction

1. Go to openverse.org
2. Click on the drop down
3. Observe that Romanian or română is not in the list of available locales

## Additional context

Originated from a discussion in our [Make WP Slack](https://wordpress.slack.com/archives/C02012JB00N/p1676049829672579).

### PR DESCRIPTION
**Pull request by dhruvkb**
## Fixes

Fixes #2170 by @AetherUnbound by improving #2172 by @dhruvkb

## Description

Even with the limit of 99 requests per second, the GlotPress download reports several 429 errors. This was not happening when the PR #2172 was made but it's happening now, because of which staging.openverse.org again lacks some languages. The situation is better, we have ~150 languages now but still not all of them (~200).

## Testing Instructions

This PR reduces the rate limit even further. It would be better if GlotPress had some official documentation around rate limits. Alternatively we could fail the deploy if the download step is incomplete?

## Checklist

- [x] My pull request has a descriptive title (not a vague title like
      `Update index.md`).
- [x] My pull request targets the _default_ branch of the repository (`main`) or
      a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible
      errors.

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by zackkrida — APPROVED** [review]
Might as well make incremental progress while we await feedback. LGTM.

**Comment by zackkrida** [comment]
@dhruvkb,I was made aware of two bulk endpoints we can use for this:

> https://translate.wordpress.org/exporter/meta/openverse/ to select the translations you want for the Openverse project.
> https://translate.wordpress.org/exporter/meta/openverse/ to get a zip with all the translations for the Openverse project.

I think this will help considerably!

**Comment by dhruvkb** [comment]
We can use the authenticated endpoint for CI, GitHub actions and maybe prod deployments but developers working locally will not have access to these endpoints unless they sign up for Make. I would very much prefer to not complicate the dev setup to add a Make account prerequisite.

**Review by obulat — APPROVED** [review]
LGTM!

**Comment by dhruvkb** [comment]
I've merged this, and opened a new issue #2186 to handle bulk downloading.

**Pull request merged**
