### PR TITLE
Add dependabot config

### LINKED ISSUE #442: Configure Dependabot using a YAML config file
## Description

For this repository, Dependabot is enabled but not configured. Adding a `.github/dependabot.yml` file should fix that. Using the file we can configure things like the update schedule and the labels to attach to the PRs made by Dependabot.

## Expectation

Dependabot should make regular, well-labeled PRs to the repository.

## Additional context

You can use the [config from the API repo](https://github.com/WordPress/openverse-api/blob/b760ca1c403265bafffda5b831033186b3d0c50f/.github/dependabot.yml) as a reference. Also see the [GitHub docs](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#about-the-dependabotyml-file) describing this config file.

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

### PR DESCRIPTION
**Pull request by obulat**
## Fixes

Fixes #442 by @dhruvkb

## Description

This PR adds the dependabot config to enable weekly dependabot update PRs. The config is copied and modified from the API repository.

## Testing Instructions

???
## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [x] My pull request targets the *default* branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [ ] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by dhruvkb — COMMENTED** [review]
I don't think this will work. Dependabot does not fully support `pnpm` yet (dependabot/dependabot-core#1736).

**Comment by obulat** [comment]
It looks like some pnpm repositories are using `pnpm` **_and_** `dependabot`: https://github.com/pnpm/action-setup . I wonder if we should try to see if it works?..

**Comment by sarayourfriend** [comment]
@obulat looking at their dependabot config it appears to just cover the github actions they're using: https://github.com/pnpm/action-setup/blob/master/.github/dependabot.yml

We could use https://github.com/renovatebot/renovate instead.

**Comment by zackkrida** [comment]
Another (probably bad) idea would be an action that only runs on dependabot PRs to update the lock file.

**Comment by dhruvkb** [comment]
Renovate seems like a good tool 👍 We should give it a go.

**Comment by obulat** [comment]
@zackkrida , It seems that we need someone with permissions to add renovate app

**Comment by zackkrida** [comment]
Great, I've requested access.

**Comment by obulat** [comment]
Closing this PR because Dependabot does not support `pnpm`. We will use [Renovate](https://github.com/renovatebot/renovate/) (#1176) instead of Dependabot because it supports `pnpm`.

**Pull request closed without merging**
