### PR TITLE
Use a modal for external sources on mobile

### LINKED ISSUE #734: Update the meta search section with the new design
## Problem
The current external sources area in search results does not follow the redesign.
**_Updated issue:_** only the mobile popup needs to be implemented for this issue.

CleanShot 2022-01-27 at 11 59 18@2x

## Description
We need to update the section with the design made on [the mockups](https://www.figma.com/file/w60dl1XPUvSaRncv1Utmnb/Openverse-Releases?node-id=133%3A6869).

### ~~Desktop version~~ Done
Meta search on desktop

### Mobile version
Instead of the current implementation in the popover, the external sources should open in a modal:
Meta search on mobile

### PR DESCRIPTION
**Pull request by obulat**
## Fixes

Fixes #734 by @panchovm

## Description

This PR uses a modal for mobile external sources. To make this possible, it also adds another modal variant that is always centered and fits the content.
If the external sources button focus ring is incorrect, it will be fixed in a separate PR that will fix buttons focus rings.

## Testing Instructions

Search for something and scroll down to see the external sources form. When you're on a mobile screen, you should see a modal if you click on the External sources button.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like
      `Update index.md`).
- [x] My pull request targets the _default_ branch of the repository (`main`) or
      a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible
      errors.

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by dhruvkb — COMMENTED** [review]
This is not rendering properly for me.
Screen Shot 2023-01-06 at 16 05 50

**Comment by obulat** [comment]
> This is not rendering properly for me. 

This PR is for external sources under the search results. I've added the screenshot to the PR description.
The external sources buttons on the "No results" page are handled in #2077.

**Comment by zackkrida** [comment]
@panchovm could you review this for design?

**Comment by panchovm** [comment]
The overall implementation looks good, but I think it is based on an old mockup version. The spacings and buttons are from depracated components of the Design Library, so it is my duty to bring up an updated solution.

Despite the design comment, I noticed an unintentional zoom-in bug. Put attention in the background of this screen recording

https://user-images.githubusercontent.com/895819/212140249-827b5ec4-3521-4833-8edc-b13e46de05f6.mp4

Should I share a design ticket with an updated version of this modal or share the mockup here? The three improvement aspects are modal width, popover item, and text styles.

**Review by panchovm — APPROVED** [review]
It works great ✨ 

I need to revisit the modal design as some styles applied are old, but that doesn't block this progress and will be tacked in a design issue.

**Comment by zackkrida** [comment]
@obulat I'm noticing one peculiarity in this PR, if I resize my browser to a mobile width I'm no longer able to scroll the page. Could merging in the recent changes to main fix this?

**Comment by obulat** [comment]
> @obulat I'm noticing one peculiarity in this PR, if I resize my browser to a mobile width I'm no longer able to scroll the page. Could merging in the recent changes to main fix this?

Were you resizing the browser to mobile width when the external sources popover is open or closed?
I rebased the PR, and I think the scroll lock works correctly now.

**Review by zackkrida — APPROVED** [review]
Works perfectly now, lgtm!

**Pull request merged**
