### PR TITLE
Disable content link when result count is zero

### LINKED ISSUE #1699: Showing the audio results link on results page when there are no results
## Description
When you search something that brings no audio results, the results page still shows the "see all audio" link. Like in [this example](https://wordpress.org/openverse/search/?q=vanagon).

## Reproduction
1. Search for "vanagon"
2. Notice has the "see all audio" link says "no results".
3. Click on it.
4. See how the page shows no results.

## Screenshots
CleanShot 2022-08-18 at 10 13 48@2x

## Resolution
- [ ] 🙋 I would be interested in resolving this bug.

### PR DESCRIPTION
**Pull request by zackkrida**
## Fixes

Fixes #1699 by @panchovm 

## Description

This PR disables the vcontent links when the result count is zero by:

- Removing their href
- Setting aria-disabled to true

This PR adds basic unit tests for this functionality and removes tests that no longer match the structure of the component. A previous version used radio buttons which was reflected in those tests.

The styling is a placeholder, waiting for design work from @panchovm. It currently sets the entire button's opacity to `.5`.

## Screenshot

CleanShot 2022-09-07 at 12 38 17@2x

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [x] My pull request targets the *default* branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added or updated tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by dhruvkb — APPROVED** [review]
Looks good! On a side-note, why did we not wait for the designs to be ready?

**Comment by zackkrida** [comment]
@dhruvkb I was going to draft this 😄. I wanted to get the logic in place and encourage the design work. I also think the priority should be `high` because it's a bug and is related to the audio beta milestone that we'd like to complete this week.

**Comment by panchovm** [comment]
Here is a version I like that is consistent with other components' disabled states.

In the example below, the 3D models link is disabled. Content icon and internal texts are `dark-charcoal-40`, the button has a `dark-charcoal-20` border, and results label changes to "No results".

imagen

What do you think?

**Comment by zackkrida** [comment]
@panchovm that looks perfect.

**Comment by zackkrida** [comment]
I updated the styles, so this is also now ready for review @panchovm 

CleanShot 2022-09-07 at 12 38 17@2x

**Comment by panchovm** [comment]
It looks excellent ✨ Here is the [Figma component](https://www.figma.com/file/GIIQ4sDbaToCfFQyKMvzr8/Openverse-Design-Library?node-id=558%3A2284) updated with this new state.

I think I have seen a pointer style change when hovering a disabled element. I might be wrong but it is like the example below.
CleanShot 2022-09-07 at 12 56 33@2x

Are we applying a similar pointer change for the disabled elements?

**Comment by zackkrida** [comment]
Good suggestion @panchovm, I've added that cursor style to the button.

**Comment by panchovm** [comment]
Wonderful. It looks great ✨

**Review by panchovm — APPROVED** [review]
Nice work 🚀

**Pull request merged**
