### PR TITLE
Remove unguarded localStorage access

### LINKED ISSUE #994: Rendering crashes in Chrome if localStorage is blocked
## Description

If localStorage is blocked then Chrome will crash.

## Reproduction

1.  Using Chromium, open settings -> security and privacy -> Block all cookies
2.  Visit the app, it will crash

## Expectation

It shouldn't crash

## Additional context

This is because of `useStorage`

## Resolution

- [x] 🙋 I would be interested in resolving this bug.

### PR DESCRIPTION
**Pull request by sarayourfriend**
## Fixes

Fixes #994 by @sarayourfriend 

## Description

Creates a new private function, `useSafeDefaultOptions` that catches errors safely.

## Testing Instructions

Follow the reproduction instructions in the issue and verify you can reproduce the issue in staging. Then checkout and run this branch with `pnpm dev` and verify that the app no longer crashes.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [x] My pull request targets the *default* branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by sarayourfriend** [comment]
@WordPress/openverse-developers Could this get reviewed? I'm looking at the sentry dashboard and the error related to this PR appears to account for a pretty significant portion of our total reported errors (11k of the 24k total errors, around 45%).

**Review by zackkrida — APPROVED** [review]
> 1. Using Chromium, open settings -> security and privacy -> Block all cookies
> 2. Visit the app, it will crash

Confirmed that this PR fixes the behavior. LGTM!

**Review by krysal — APPROVED** [review]
Fortunately it doesn't break the app in Chrome or Firefox but happy to have it fixed in Chromium as well.

**Comment by sarayourfriend** [comment]
> Fortunately it doesn't break the app in Chrome or Firefox but happy to have it fixed in Chromium as well.

Interesting that it doesn't break in Chrome proper! Most of the reports in Sentry show it happening on regular Chrome on Windows, but I just tested that in a VM and it also doesn't crash (despite throwing a security error in the console when I try to access `localStorage`). Very curious!

**Pull request merged**
