### PR TITLE
Create the audio track component

### LINKED ISSUE #104: [Audio] Create 'track' component
> Note: this screenshot is an example and may not reflect the final UI, but will reflect the data.

CleanShot 2021-07-30 at 17 08 35@2x

We should create a new `<Track />` component. this component needs to display:

- display track name, nuxt-linked to the single result view
- display tags that link to the `/search/audio` view with the user's query and a filter for the selected tag
- manage its own play/pause state internally
- a html audio element to play the track
- a timestamp for the track
- the waveform for the track (at this point i think custom waveform rendering with svg (since our new waveform design is pretty simple) will be the best approach, but we will discuss more

### PR DESCRIPTION
**Pull request by dhruvkb**
## Fixes

Fixes #104 by @zackkrida 

## Description
This PR creates the audio track component and any other components needed by it.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [ ] My pull request targets the *default* branch of the repository (`main` or `master`).
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added or updated tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by dhruvkb** [comment]
image

**Comment by zackkrida** [comment]
So happy to see the resampling work, amazing

**Comment by zackkrida** [comment]
Added a quick event handler to make the progress user-settable. you don't have to go with this implementation of course :) 

CleanShot 2021-08-14 at 06 39 40

https://github.com/WordPress/openverse-frontend/pull/128

we'd do the same approach with a hover event for the grey preview state

CleanShot 2021-08-14 at 06 48 28@2x

**Comment by dhruvkb** [comment]
I just finished that same stuff locally @zackkrida. Now I'm 
- sad that part of both our efforts will be wasted
- happy that the final thing will be better than either of our implementations

**Comment by dhruvkb** [comment]
@zackkrida I made some tweaks and merged your PR, thanks for chipping in!

**Comment by zackkrida** [comment]
What's important is that we had fun! Haha, it is the weekend after all. Excited to look at the approach you went with.

**Comment by zackkrida** [comment]
By the way @dhruvkb, this is looking amazing, and don't worry, I won't inturrupt your work with contributions of my own 😆.

I'm realizing we need @panchovm to design a state for when you go seek _backwards_ over the yellow bar. maybe the bars could be white or something? not sure. If you need me to describe the state we need better @panchovm I can elaborate next week.

**Comment by dhruvkb** [comment]
Hahaha, I'm heading off to sleep now, feel free to add any changes you find!

**Comment by dhruvkb** [comment]
I tweaked the appearance a little bit to change how the seek process looks when seeking behind progress in d6113cb.

**Comment by panchovm** [comment]
All this looks awesome. Thank you both. Regarding going backward, I was thinking of keeping the same black bars interactions. The yellow background fills the area slowly as the seconds pass, while the black bars show what time the user wants to start playing, no matter if the yellow area is ahead or behind. 

The wave area (gray bars) works independently of the playing area (yellow background) when the user hovers the whole audio section.

I hope I explained myself correctly.

**Comment by dhruvkb** [comment]
@panchovm I think I got what you mean. That's great because d6113cb implements exactly the same idea that you mentioned :tada:!

**Comment by zackkrida** [comment]
@panchovm for reference, here is the current implementation:


https://user-images.githubusercontent.com/6351754/129737427-a13b0c9e-7db0-430b-99ea-29b873b19ee5.mp4

**Comment by zackkrida** [comment]
@dhruvkb I cleaned up the git history here, you might want to `git branch -D track` and `git checkout track` locally.

**Comment by zackkrida** [comment]
In `AudioTrack.vue` we might want to have something like this, as a fallback for when peaks data doesn't exist:


```diff
     <Waveform
+       v-if="audio.peaks"
        class="h-30 w-full"
        :is-ready="isReady"
        :current-time="currentTime"
        :duration="duration"
        :peaks="audio.peaks"
        @seeked="setPosition"
      />
```

Otherwise this is looking really good. Do we want to include all a11y work here or in a subsequent pr?

**Comment by dhruvkb** [comment]
Subsequent PR would be good as getting the Storybook merged allows other components to be developed on the side.

**Comment by dhruvkb** [comment]
@zackkrida your suggestion about removing the waveform in the absence of peaks will need a design update because the waveform is both the progress and the seek bar. Without it, we need an alternative way to serve these functions.

CC: @panchovm

**Comment by zackkrida** [comment]
> @zackkrida your suggestion about removing the waveform in the absence of peaks will need a design update because the waveform is both the progress and the seek bar. Without it, we need an alternative way to serve these functions.
> 
> 
> 
> CC: @panchovm 

I'm also fine with some kind of way to guarantee we have the waveform elsewhere in the stack. If we can assume we have the audio, we can assume we have the waveform

**Review by zackkrida — APPROVED** [review]
I still just want the bars to be closer to 3/4 of the height rather than 2/3. This is such good work and brings us much much closer to launching audio

**Comment by dhruvkb** [comment]
@zackkrida increased the height to 3/4 of the total in 47bf213!

**Comment by zackkrida** [comment]
Looks great

**Comment by dhruvkb** [comment]
Are we following the two reviews to merge rule for PRs to `audio`?

**Review by krysal — APPROVED** [review]
It's so exciting to see the track component playing the audio! It looks simple but at the same time, it has so many carefully thought out and cared details. Excellent work, thanks!

**Pull request merged**
