### PR TITLE
Ignore wp-locales file

### LINKED ISSUE #579: Ignore changes to `wp-locales.json`
## Problem

Currently, `wp-locales.json` is updated every time `pnpm run dev` is run, and whenever a translation percentage changes for any locale, `wp-locales.json` shows as changed. This adds noise to every PR.

## Description

We can add `wp-locales.json` to .gitignore so that it is not committed with every PR.

## Additional context

We have done the same for `/src/locales/scripts/valid-locales.json`

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

### PR DESCRIPTION
**Pull request by zackkrida**
## Fixes

Fixes #579 by @obulat 

## Description

Deletes and stops tracking the wp-locales.json file. This file is created as part of a postinstall hook, so if you're ever missing it for some reason after this you will need to `pnpm i` to restore it. This should reduce a lot of noise in our PR reviews and diffs.

## Checklist

- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [ ] My pull request targets the *default* branch of the repository (`main`) or a parent feature branch.
- [ ] My commit messages follow [best practices][best_practices].
- [ ] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by obulat** [comment]
Is there a way to check if the `wp-locales.json` file exists in `get-translations.js`, and if not, call the `create-wp-locale-list.js` script?

**Comment by zackkrida** [comment]
@obulat that's a good idea, we can do that.

**Review by AetherUnbound — APPROVED** [review]
I don't have much to say on this, but it looks good! :smile:

**Review by krysal — APPROVED** [review]
I will really appreciate stopping tracking this file.

**Comment by zackkrida** [comment]
I need to implement @obulat's suggestion before merging this, will do tomorrow!

**Comment by zackkrida** [comment]
Updated to make sure the files are built when needed.

**Comment by obulat** [comment]
I haven't seen this PR before it was merged, but thank you so much for working on it, @zackkrida !

**Pull request merged**
