### PR TITLE
Use 's' audio track layout for mobile

### LINKED ISSUE #668: Mobile audio search result is using wrong layout size
## Description

Audio search result is incorrectly using `m` audio track size, instead of `s`. Because of this, the track doesn't fit in the screen, and the play button isn't visible, too:

Screen Shot 2022-01-21 at 1 03 59 PM

## Reproduction

1. Run the app and open it in a 350px-wide screen.
2. See error.

## Expectation

Mobile screen should use the small layout, and the play button should be visible

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

### PR DESCRIPTION
**Pull request by obulat**
## Fixes

Fixes #668 by @obulat

## Description

This PR uses 's' layout for screens smaller than `md`. This layout doesn't show the audio track, which is shown at the bottom of the screen instead.

Screen Shot 2022-01-21 at 2 20 29 PM

## Testing Instructions

Run the app and search for audio on a narrow screen. You should not see a large play button.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [x] My pull request targets the *default* branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by dhruvkb — APPROVED** [review]
LGTM!

**Review by zackkrida — APPROVED** [review]
👍

**Comment by panchovm** [comment]
It works great and smoothly. I just noticed three things.
1. I'm not sure if we set `130%` for the `line-height` of **Description bold** style, converted to rem value. It seems bigger, as the red area in the image below shows.
2. The spacing between title, author, and other meta-data info is inconsistent; blue area in the image attached. The mockup has a `8px` spacing separating those three rows.
3. The spacing between CC icons should be `2px`. 

<image src="https://user-images.githubusercontent.com/895819/150529614-99c19b2a-4fca-4db8-8311-dc0c36176be6.png" width="400">

**Comment by zackkrida** [comment]
Thanks @panchovm I've made a new issue for those spacing issues [here](https://github.com/WordPress/openverse-frontend/issues/672)

**Pull request merged**
