### PR TITLE
Fix global audio rtl close placement

### LINKED ISSUE #779: Global audio player RTL is slightly broken
## Description

The RTL version fo the global audio player is slightly broken.

## Reproduction

1. Checkout `main`, run `pnpm dev` and visit `/ar/search/audio?q=birds` with a small width viewport
2. Click "play" button on one of the audio results so that global audio opens
3. Note the `X` to close the global audio player is over the cover art.

## Expectation

The `X` should be on the opposite side.

## Screenshots

Captura de Tela 2022-02-01 às 14 53 49

## Additional context

Found while testing https://github.com/WordPress/openverse-frontend/pull/773

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

### PR DESCRIPTION
**Pull request by zackkrida**
## Fixes

Fixes #779 by @sarayourfriend 

## Description

Switches from using `end-0`, which doesn't seem to work correctly, to explicitly using `rtl:left-0 ltr:right-0`. 

I think the `end-0` css logic looks for _any_ parent element that doesn't have a `dir` applied, so both of these styles are applied at once and specificity wins:

```css
:not([dir="rtl"]) .end-0 {
    right: 0;
}

[dir="rtl"] .end-0 {
    left: 0;
}
```

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [x] My pull request targets the *default* branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by sarayourfriend** [comment]
This should be fixed in the tailwindcss-rtl library once https://github.com/20lives/tailwindcss-rtl/issues/44 is closed I think?

In any case, using the built in Tailwind RTL/LTR utilities (even though they're experimental and liable to change) seems like a good way to fix this for now.

**Review by sarayourfriend — APPROVED** [review]
LGTM! Tested locally in both RTL and LTR modes and it works great. Will pair very nicely with #773.

**Comment by zackkrida** [comment]
>  20lives/tailwindcss-rtl#44

Yep, that's exactly it, nice find! Glad to have it referenced here.

**Review by dhruvkb — APPROVED** [review]
Why wouldn't `end-0` work?

**Pull request merged**
