### PR TITLE
Replace PDM logo

### LINKED ISSUE #409: Wrong icon for Public Domain tool
## Description

We are using the wrong icon for works marked with Public Domain Mark. The correct iconography is the one shown on the [Creative Commons site](https://creativecommons.org/publicdomain/mark/1.0/) about this tool.

## Reproduction

1. Run Storybook and navigate to the `License > PDM` component
2. See this icon
CleanShot 2021-11-11 at 15 51 48@2x

when it should be

CleanShot 2021-11-11 at 15 51 13@2x

you can find the SVG icon [here](https://github.com/creativecommons/vocabulary/blob/main/src/assets/icons/cc-pdm.svg).

## Expectation

Replace the "PD" icon with the correct one to be consistent with the official brand of the tool and the rest of components. We are showing the correct icon on the image detail page.

## Resolution

- [x] 🙋 I would be interested in resolving this bug.

### PR DESCRIPTION
**Pull request by krysal**
## Fixes

Fixes #409 by @krysal

## Description

This PR changes the icon for the **Public Domain Mark** _tool_ (this is not exactly a license) and prefixes the `<License>` component with a `V` as per our new standard to follow Vue recommendation to not name components with a single word. Also, adds the CC logo for the **CC0** tool, like the rest of the licenses.

## Testing Instructions

Run storybook and observe changes in Components > VLicense > PDM route.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [x] My pull request targets the *default* branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by krysal** [comment]
@dhruvkb I added the icon from [Font Awesome](https://fontawesome.com/v5.15/icons/creative-commons-pd?style=brands) as you suggested but changing only the viewBox naively breaks it. What do you do to add these icons correctly?

**Comment by dhruvkb** [comment]
Yeah, sorry for the wrong resource I shared @krysal. I think using the [SVG from Vocabulary](https://github.com/creativecommons/vocabulary/blob/main/src/assets/icons/cc-pdm.svg) might be better as it matches the `viewBox` of the other icons. I suspect they were taken from Vocabulary as well 😆.

**Comment by krysal** [comment]
I was thinking there was a specific process of scaling, transforming and/or repositioning the SVG, lol! Glad that it is a more straightforward solution. Thanks!

Fixed and ready to review.

**Review by sarayourfriend — APPROVED** [review]
Tested locally and it looks great!

**Review by zackkrida — APPROVED** [review]
nice

**Pull request merged**
