### PR TITLE
Removed unused image assets

### LINKED ISSUE #396: Clean up image assets
## Problem

Currently a number of image assets (including SVGs, JPGs and PNGs) are stored directly under `src/assets/`. This is in direct contrast to a number of organised image assets in `src/assets/icons/` and `src/assets/licenses/`.

## Description

The goal is to clean up the folder. Remove unused assets and organise the used ones into a proper folder structure. One way to do so would be to put the assets for the providers into one folder. Another would be to collect the assets for the CC licenses in another folder. 

## Alternatives

Deleting the unused ones would be a good start as cleaning up the rest would be easier.

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

### PR DESCRIPTION
**Pull request by MukulKolpe**
## Description

Removed unused image assets (including SVGs, JPGs and PNGs) from `src/assets/`
## Checklist

- [X] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [X] My pull request targets the *default* branch of the repository (`main`) or a parent feature branch.
- [X] My commit messages follow [best practices][best_practices].
- [ ] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [X] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by MukulKolpe** [comment]
How to add `aspect: code` and `goal: internal improvements` labels?

**Review by dhruvkb — COMMENTED** [review]
@MukulKolpe great work so far, it's quite nice to see the unused assets gone from the codebase. But there are many more unused image assets. Please also check and delete them.

**Comment by MukulKolpe** [comment]
@dhruvkb I checked a few times But all the images are used somewhere. Can you please share 1-2 more images that aren't used?

**Comment by dhruvkb** [comment]
The provider logos in `src/assets/` (file names containing suffix `logo.svg`) are also unused now. I think they can safely be removed.

**Review by zackkrida — CHANGES_REQUESTED** [review]
@MukulKolpe `src/assets/logo.svg`  needs to be restored, or the app fails to run:
CleanShot 2021-11-18 at 13 43 02@2x

**Review by zackkrida — APPROVED** [review]

**Review by krysal — APPROVED** [review]
Looks good to me. Thanks, @MukulKolpe!

**Pull request merged**
