### PR TITLE
Remove ring offset to reduce ring thickness

### LINKED ISSUE #2129: Focus outline thickness is incorrect in the 'Clear filters' button
## Description

The 'Clear filters' button which only appears if a filter is applied has a focus outline that's thicker for mouse hover but normal for keyboard focus.

## Reproduction

1. Search for somthing.
2. Apply a filter from the sidebar.
3. Try different combinations of:
  - Focusing the 'Clear filters' button using the keyboard.
  - Hovering over it with a mouse.
5. See the strange focus outlines.

## Screenshots

https://user-images.githubusercontent.com/16580576/216288053-c78d1212-3727-46a4-93ea-2cc1d7c0d2d4.mov

## Environment

- Device: MacBook Pro M1
- OS: macOS Ventura 13.1
- Browser: Firefox
- Version: 109.1

## Additional context

This does not seem to be a browser-specific issue.

### PR DESCRIPTION
**Pull request by dhruvkb**
## Fixes

Fixes #2129 by @dhruvkb

## Description

This PR removes the ring offset from the 'Clear filters' button because that causes the ring to appear thicker. Now the thickness of the focus ring is consistent with the rest of the app.

## Testing Instructions

0. Check out the PR and run the dev server.
1. Search for a term.
2. Apply a filter. You will see the Clear filters button.
3. Hover over the button, note the outline style.
4. Focus the button with the keyboard, note the outline style.
5. The style should be the same.

## Screenshots

https://user-images.githubusercontent.com/16580576/217169268-b7875fb7-a412-43e4-9d27-ac6aa0fb6847.mov

^ The first occurrence is the move hover and the second is the keyboard focus

## Checklist

- [x] My pull request has a descriptive title (not a vague title like
      `Update index.md`).
- [x] My pull request targets the _default_ branch of the repository (`main`) or
      a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible
      errors.

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by panchovm** [comment]
This component would look great if it changes to [Link's Figma component](https://www.figma.com/file/GIIQ4sDbaToCfFQyKMvzr8/Openverse-Design-Library?node-id=3667%3A9753&t=nDtLsLleJq5e6Yjf-4). The style is almost the same, and it adds consistency to the upcoming style revisit goal.

CleanShot 2023-02-07 at 11 30 42@2x

I hope it stays within the same purpose of this PR.

**Comment by dhruvkb** [comment]
@panchovm we could make it look like a Link but since it is a button some of the interactions would be different. For example, if you hover over a link, it might change text color or show an underline but the same interactions on a button would look very out of place.

**Comment by panchovm** [comment]
Let's keep it as VButton then. I am currently working on a design proposal for improving the VButton style across the site and Figma documentation. So leveraging this and other similar cases in the idea I am handling.

Thanks @dhruvkb.

**Comment by dhruvkb** [comment]
I'll undraft this then and we can refine the UI with the rest of the button update project.

**Review by obulat — APPROVED** [review]
Thank you for the fix!

**Pull request merged**
