### PR TITLE
Make audio/image pages without ids show a 404

### LINKED ISSUE #496: Going to `/photos/` without an id should not fetch
## Description

If you go to `/search/image/`, you will first see the skeleton of the Single result page, and then be redirected to an error page. 
## Reproduction

1. Run the app with `npm run dev`,  and go to `localhost:8443/photos/`
or 
2. go to `https://wordpress.org/openverse/photos/`
3. See error.

## Expectation

I am not sure what should happen here. Some ideas:
1. We need to check the image ID in the request. We could also probably use a UUID regex, since we do not have any other image IDs. 
2. If the image ID in the request is invalid, we should redirect to the home page? or the 404 page? How do we indicate that the user was redirected because of an invalid URL?

## Screenshots

noId

You will also see the

<details>

<summary>following error messages in the console</summary>

```
[Vue warn]: Invalid prop: type check failed for prop "imageId". Expected String, got Undefined 

found in

---> <RelatedImages> at src/components/ImageDetails/RelatedImages.vue
       <PhotoDetailPage> at src/pages/image/_id.vue
         <Nuxt>
           <EmbeddedWithNavSearch> at src/layouts/with-nav-search.vue
             <Root> client.js:57
Error in fetch(): Error: [RWV] ImageService.getRelatedImages() id parameter required to retrieve related images.
    at Object.getRelatedMedia (server.js:38356:13)
    at server.js:37573:36
    at server.js:7170:39
    at Array.map (<anonymous>)
    at VueComponent.callFetches (server.js:7168:37)
    at useRelated (server.js:37578:3)
    at setup (server.js:12051:81)
    at mergedSetupFn (/Users/obulat/Documents/openverse/openverse-frontend/node_modules/@vue/composition-api/dist/vue-composition-api.common.js:2099:113)
    at /Users/obulat/Documents/openverse/openverse-frontend/node_modules/@vue/composition-api/dist/vue-composition-api.common.js:1915:23
    at activateCurrentInstance (/Users/obulat/Documents/openverse/openverse-frontend/node_modules/@vue/composition-api/dist/vue-composition-api.common.js:1830:16)
    ```

</details>

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

### PR DESCRIPTION
**Pull request by sarayourfriend**
## Fixes

Fixes #496 by @obulat 

## Description

Adds an `index.vue` to the `image` and `audio` page directories so that we can render a 404 page when a single result route without an id is hit.

I'm not sure if this is really the _right_ way to do this... I couldn't find any solid evidence about this and redirecting to `/404` seems incorrect for some reason. If we prefer that though, we can do that instead of this. I do like that this is a little more on the "declarative" side of things rather than programatically testing the route.

## Testing Instructions

Checkout the branch and run `pnpm dev`. Visit `/image/` without an id and `/audio/` without an id and verify that they show the 404 page.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [x] My pull request targets the *default* branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by zackkrida — APPROVED** [review]
I quite like this approach, as it also allows us to more easily make our error page support different error types, not just 404s. Something like:

```vue
 <VFourOhFour v-if="error.code === '404'" :error="error" />
```

**Review by dhruvkb — APPROVED** [review]
I like the name `VFourOhFour`. @panchovm what are your thoughts on i18n-ifying the "Oops" in the future?

**Comment by zackkrida** [comment]
My instinct would be to keep "Oops" as an sr-only decorative choice. I think it'd be really difficult to style with different string lengths.

**Comment by panchovm** [comment]
Agree with @zackkrida. Besides, the design intends to be use across the WP site. Although I like the idea and worth raising it once people start redesigning other site sections.

**Pull request merged**
