### PR TITLE
Move new homepage and 404 to the `default` layout

### PR DESCRIPTION
**Pull request by obulat**
## Fixes

Related to #1433 by @panchovm

## Description

This PR simplifies the code for page layouts for the new designs. It moves the home and 404 pages to the `default` layout, so there's no more need to add header/footer to them as they are available in the layout.

This PR does not fix the content switcher on the home page.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like
      `Update index.md`).
- [x] My pull request targets the _default_ branch of the repository (`main`) or
      a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible
      errors.

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by dhruvkb — APPROVED** [review]
Does merging this PR remove the need to merge #2076? The description in #2076 says "It's easier to just merge this PR as part of https://github.com/WordPress/openverse-frontend/pull/2075."

**Comment by obulat** [comment]
> Does merging this PR remove the need to merge #2076? The description in #2076 says "It's easier to just merge this PR as part of #2075."

We can do it that way, yes. I'll update the description.

**Comment by zackkrida** [comment]
@obulat I noticed two oddities:

1. When going from search results to home, the background changes to yellow before the path changes, so for a second the user sees a yellow background behind the search results. This is because the entire page no longer re-renders. We could possibly force a rerender probably by setting a `key` of the page slug on the root of the default layout. 
2. The preferences page has a yellow background. Not a huge deal but probably quick to fix.

**Review by zackkrida — APPROVED** [review]
Looks good!

**Pull request merged**
