### PR TITLE
Fix PO generation workflow

### PR DESCRIPTION
**Pull request by sarayourfriend**
## Fixes

Follow up to #1535 @sarayourfriend 

## Description

As @zackkrida pointed out in the original #1051 issue, the workflow is not working due to not being able to checkout the translations branch. I'm trying to fix that here.

## Testing Instructions

Checkout the workflow runs and confirm that it works in this PR.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [x] My pull request targets the *default* branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [N/A] I added or updated tests for the changes I made (if applicable).
- [N/A] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by sarayourfriend** [comment]
Okay, there was a post-run issue with the setup-node-env that seems to just be an intermittent failure. But the rest of the workflow ran successfully and you can see the commit it made here: https://github.com/WordPress/openverse-frontend/commit/04c5da3088b0416318db00ad1eabdce3bd93c3ca

Here is the run in question: https://github.com/WordPress/openverse-frontend/runs/7124031759?check_suite_focus=true

I'm removing the testing code now and then this will be ready for review. Whomever is second to approve it feel free to merge it at your leisure if it is after EOD for me.

**Comment by sarayourfriend** [comment]
Actually, I realized why the cleanup failed. Details in the message attached to this commit: https://github.com/WordPress/openverse-frontend/pull/1550/commits/1146aa4311f859c8569fb3f2bfdd52e2295be3d4

**Review by obulat — APPROVED** [review]
Nice!

**Review by zackkrida — APPROVED** [review]
Ah, multiple scoped checkouts should be faster than my suggestion. This looks right 🤞

**Pull request merged**
