### PR TITLE
Try adding .pot file on every commit

### PR DESCRIPTION
**Pull request by obulat**
## Fixes

Related to #1051 by @dhruvkb

## Description

I'm not sure if it will work, but it's worth a try. With this PR, `pnpm i18n:generate-pot` should run on every commit. If the file is generated, then it should be added to the commit.

## Testing Instructions

I don't know how to actually test it.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [x] My pull request targets the *default* branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by sarayourfriend** [comment]
This is going to make rebasing a huge pain :slightly_smiling_face: Instead of having to deal with discrete `Update POT` commits like we do now (which are sometimes numerous) we'll have to do "something" on _every single commit_ if we change the POT by the last one on the branch being rebased.

**Review by krysal — COMMENTED** [review]
Yeah, I thought we agree to not do this kind of automatic updates to the .pot file, turns out to be more trouble than it helps sadly.

**Comment by sarayourfriend** [comment]
I wonder if it would be possible for us to have the POT file in a different repository (or maybe just a special protected branch similar to gh-pages?) that is pushed to automatically by GH Action every time we merge to main.

**Comment by obulat** [comment]
Thank you for the explanation, I was not aware of the problems it would create. I'm just really annoyed with the "Update pot file" commits :)

**Comment by sarayourfriend** [comment]
> Thank you for the explanation, I was not aware of the problems it would create. I'm just really annoyed with the "Update pot file" commits :)

Me too. I think given the nature of how the POT file is generated,  I'm going to open an issue for us to push the translation files into a special branch.

**Pull request closed without merging**
