### PR TITLE
Update names and references of `AudioDetails-` components

### LINKED ISSUE #581: Audio details page components names need to be updated
## Description

Two components used in the audio details page were using the Nuxt's automatic component resolution, and are not loading now. Nuxt allows to use a `File` component inside the `Directory` directory using `DirectoryFile.vue` as component name, without registering or importing it. However, we have recently turned off this feature to ensure clarity of where the code comes from. This is why two components on `AudioDetails` page are not loaded correctly: `Table` and `Related`. They need to be renamed, with a `V-` prefix added, too, and the import statements should be added to the `AudioDetails` page.
​

## Reproduction

1. Open audio detail page.
2. Look in the console
3. See error.

```
[Vue warn]: Unknown custom element: <AudioDetailsTable> - did you register the component correctly? For recursive components, make sure to provide the "name" option.
[Vue warn]: Unknown custom element: <AudioDetailsRelated> - did you register the component correctly? For recursive components, make sure to provide the "name" option.
```

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

### PR DESCRIPTION
**Pull request by dhruvkb**
## Fixes

Fixes #581 by @obulat

## Description

This PR
- renames the `.vue` files of `AudioDetails/` components to add the `VAudioDetails-` prefix
- matches the component names in the `name` field to the file name
- updates the usages of the components to the updated names to avoid the need of explicit imports

## Testing Instructions

- 0. Checkout the branch and run the dev server.
- 0. Go to the audio detail page.
- 0. Verify that all components (`VAudioDetailsTable`, `VAudioDetailsTags`, `VAudioDetailsRelated`) are rendered as expected.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [x] My pull request targets the *default* branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by obulat — APPROVED** [review]
It's great that it works now, but the names are very long :( 
How about renaming the components, something like:
VAudioDetailsRelated -> VRelatedAudio
VAudioDetailsTags -> VAudioTags
VAudioDetailsTable -> VAudioDetails ?

**Comment by dhruvkb** [comment]
I couldn't agree more. Short names ftw!

**Review by krysal — APPROVED** [review]
LGTM

**Review by zackkrida — APPROVED** [review]
Great!

**Pull request merged**
